// Code generated by protoc-gen-go. DO NOT EDIT.
// source: kinda-outgoing.proto

package KindaGRPC

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type DTOValidationErrorCodePB int32

const (
	DTOValidationErrorCodePB_NOT_NULL            DTOValidationErrorCodePB = 0
	DTOValidationErrorCodePB_NOT_EMPTY           DTOValidationErrorCodePB = 1
	DTOValidationErrorCodePB_PATTERN_NOT_MATCHED DTOValidationErrorCodePB = 2
	DTOValidationErrorCodePB_NOT_ACCEPTED        DTOValidationErrorCodePB = 3
	DTOValidationErrorCodePB_WRONG_ARRAY_SIZE    DTOValidationErrorCodePB = 4
	DTOValidationErrorCodePB_ENUM_NOT_ACCEPTED   DTOValidationErrorCodePB = 5
)

var DTOValidationErrorCodePB_name = map[int32]string{
	0: "NOT_NULL",
	1: "NOT_EMPTY",
	2: "PATTERN_NOT_MATCHED",
	3: "NOT_ACCEPTED",
	4: "WRONG_ARRAY_SIZE",
	5: "ENUM_NOT_ACCEPTED",
}

var DTOValidationErrorCodePB_value = map[string]int32{
	"NOT_NULL":            0,
	"NOT_EMPTY":           1,
	"PATTERN_NOT_MATCHED": 2,
	"NOT_ACCEPTED":        3,
	"WRONG_ARRAY_SIZE":    4,
	"ENUM_NOT_ACCEPTED":   5,
}

func (x DTOValidationErrorCodePB) String() string {
	return proto.EnumName(DTOValidationErrorCodePB_name, int32(x))
}

func (DTOValidationErrorCodePB) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_cb4c0e7f06dd050b, []int{0}
}

type EmptyResponsePB struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EmptyResponsePB) Reset()         { *m = EmptyResponsePB{} }
func (m *EmptyResponsePB) String() string { return proto.CompactTextString(m) }
func (*EmptyResponsePB) ProtoMessage()    {}
func (*EmptyResponsePB) Descriptor() ([]byte, []int) {
	return fileDescriptor_cb4c0e7f06dd050b, []int{0}
}

func (m *EmptyResponsePB) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EmptyResponsePB.Unmarshal(m, b)
}
func (m *EmptyResponsePB) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EmptyResponsePB.Marshal(b, m, deterministic)
}
func (m *EmptyResponsePB) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EmptyResponsePB.Merge(m, src)
}
func (m *EmptyResponsePB) XXX_Size() int {
	return xxx_messageInfo_EmptyResponsePB.Size(m)
}
func (m *EmptyResponsePB) XXX_DiscardUnknown() {
	xxx_messageInfo_EmptyResponsePB.DiscardUnknown(m)
}

var xxx_messageInfo_EmptyResponsePB proto.InternalMessageInfo

type StringResponsePB struct {
	Value                string   `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StringResponsePB) Reset()         { *m = StringResponsePB{} }
func (m *StringResponsePB) String() string { return proto.CompactTextString(m) }
func (*StringResponsePB) ProtoMessage()    {}
func (*StringResponsePB) Descriptor() ([]byte, []int) {
	return fileDescriptor_cb4c0e7f06dd050b, []int{1}
}

func (m *StringResponsePB) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StringResponsePB.Unmarshal(m, b)
}
func (m *StringResponsePB) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StringResponsePB.Marshal(b, m, deterministic)
}
func (m *StringResponsePB) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StringResponsePB.Merge(m, src)
}
func (m *StringResponsePB) XXX_Size() int {
	return xxx_messageInfo_StringResponsePB.Size(m)
}
func (m *StringResponsePB) XXX_DiscardUnknown() {
	xxx_messageInfo_StringResponsePB.DiscardUnknown(m)
}

var xxx_messageInfo_StringResponsePB proto.InternalMessageInfo

func (m *StringResponsePB) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

// [START authorization]
type AuthResponsePB struct {
	Sid                  string   `protobuf:"bytes,2,opt,name=sid,proto3" json:"sid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AuthResponsePB) Reset()         { *m = AuthResponsePB{} }
func (m *AuthResponsePB) String() string { return proto.CompactTextString(m) }
func (*AuthResponsePB) ProtoMessage()    {}
func (*AuthResponsePB) Descriptor() ([]byte, []int) {
	return fileDescriptor_cb4c0e7f06dd050b, []int{2}
}

func (m *AuthResponsePB) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AuthResponsePB.Unmarshal(m, b)
}
func (m *AuthResponsePB) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AuthResponsePB.Marshal(b, m, deterministic)
}
func (m *AuthResponsePB) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AuthResponsePB.Merge(m, src)
}
func (m *AuthResponsePB) XXX_Size() int {
	return xxx_messageInfo_AuthResponsePB.Size(m)
}
func (m *AuthResponsePB) XXX_DiscardUnknown() {
	xxx_messageInfo_AuthResponsePB.DiscardUnknown(m)
}

var xxx_messageInfo_AuthResponsePB proto.InternalMessageInfo

func (m *AuthResponsePB) GetSid() string {
	if m != nil {
		return m.Sid
	}
	return ""
}

type DTOValidationResponsePB struct {
	Code                 DTOValidationErrorCodePB `protobuf:"varint,1,opt,name=code,proto3,enum=KindaGRPC.DTOValidationErrorCodePB" json:"code,omitempty"`
	DtoName              string                   `protobuf:"bytes,2,opt,name=dtoName,proto3" json:"dtoName,omitempty"`
	DtoField             string                   `protobuf:"bytes,3,opt,name=dtoField,proto3" json:"dtoField,omitempty"`
	Pattern              string                   `protobuf:"bytes,4,opt,name=pattern,proto3" json:"pattern,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                 `json:"-"`
	XXX_unrecognized     []byte                   `json:"-"`
	XXX_sizecache        int32                    `json:"-"`
}

func (m *DTOValidationResponsePB) Reset()         { *m = DTOValidationResponsePB{} }
func (m *DTOValidationResponsePB) String() string { return proto.CompactTextString(m) }
func (*DTOValidationResponsePB) ProtoMessage()    {}
func (*DTOValidationResponsePB) Descriptor() ([]byte, []int) {
	return fileDescriptor_cb4c0e7f06dd050b, []int{3}
}

func (m *DTOValidationResponsePB) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DTOValidationResponsePB.Unmarshal(m, b)
}
func (m *DTOValidationResponsePB) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DTOValidationResponsePB.Marshal(b, m, deterministic)
}
func (m *DTOValidationResponsePB) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DTOValidationResponsePB.Merge(m, src)
}
func (m *DTOValidationResponsePB) XXX_Size() int {
	return xxx_messageInfo_DTOValidationResponsePB.Size(m)
}
func (m *DTOValidationResponsePB) XXX_DiscardUnknown() {
	xxx_messageInfo_DTOValidationResponsePB.DiscardUnknown(m)
}

var xxx_messageInfo_DTOValidationResponsePB proto.InternalMessageInfo

func (m *DTOValidationResponsePB) GetCode() DTOValidationErrorCodePB {
	if m != nil {
		return m.Code
	}
	return DTOValidationErrorCodePB_NOT_NULL
}

func (m *DTOValidationResponsePB) GetDtoName() string {
	if m != nil {
		return m.DtoName
	}
	return ""
}

func (m *DTOValidationResponsePB) GetDtoField() string {
	if m != nil {
		return m.DtoField
	}
	return ""
}

func (m *DTOValidationResponsePB) GetPattern() string {
	if m != nil {
		return m.Pattern
	}
	return ""
}

type CollectionDTOValidationResponsePB struct {
	DtoValidation        []*DTOValidationResponsePB `protobuf:"bytes,1,rep,name=dtoValidation,proto3" json:"dtoValidation,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                   `json:"-"`
	XXX_unrecognized     []byte                     `json:"-"`
	XXX_sizecache        int32                      `json:"-"`
}

func (m *CollectionDTOValidationResponsePB) Reset()         { *m = CollectionDTOValidationResponsePB{} }
func (m *CollectionDTOValidationResponsePB) String() string { return proto.CompactTextString(m) }
func (*CollectionDTOValidationResponsePB) ProtoMessage()    {}
func (*CollectionDTOValidationResponsePB) Descriptor() ([]byte, []int) {
	return fileDescriptor_cb4c0e7f06dd050b, []int{4}
}

func (m *CollectionDTOValidationResponsePB) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CollectionDTOValidationResponsePB.Unmarshal(m, b)
}
func (m *CollectionDTOValidationResponsePB) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CollectionDTOValidationResponsePB.Marshal(b, m, deterministic)
}
func (m *CollectionDTOValidationResponsePB) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CollectionDTOValidationResponsePB.Merge(m, src)
}
func (m *CollectionDTOValidationResponsePB) XXX_Size() int {
	return xxx_messageInfo_CollectionDTOValidationResponsePB.Size(m)
}
func (m *CollectionDTOValidationResponsePB) XXX_DiscardUnknown() {
	xxx_messageInfo_CollectionDTOValidationResponsePB.DiscardUnknown(m)
}

var xxx_messageInfo_CollectionDTOValidationResponsePB proto.InternalMessageInfo

func (m *CollectionDTOValidationResponsePB) GetDtoValidation() []*DTOValidationResponsePB {
	if m != nil {
		return m.DtoValidation
	}
	return nil
}

type GeoDistancePB struct {
	Distance             float64  `protobuf:"fixed64,1,opt,name=distance,proto3" json:"distance,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GeoDistancePB) Reset()         { *m = GeoDistancePB{} }
func (m *GeoDistancePB) String() string { return proto.CompactTextString(m) }
func (*GeoDistancePB) ProtoMessage()    {}
func (*GeoDistancePB) Descriptor() ([]byte, []int) {
	return fileDescriptor_cb4c0e7f06dd050b, []int{5}
}

func (m *GeoDistancePB) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GeoDistancePB.Unmarshal(m, b)
}
func (m *GeoDistancePB) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GeoDistancePB.Marshal(b, m, deterministic)
}
func (m *GeoDistancePB) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GeoDistancePB.Merge(m, src)
}
func (m *GeoDistancePB) XXX_Size() int {
	return xxx_messageInfo_GeoDistancePB.Size(m)
}
func (m *GeoDistancePB) XXX_DiscardUnknown() {
	xxx_messageInfo_GeoDistancePB.DiscardUnknown(m)
}

var xxx_messageInfo_GeoDistancePB proto.InternalMessageInfo

func (m *GeoDistancePB) GetDistance() float64 {
	if m != nil {
		return m.Distance
	}
	return 0
}

func init() {
	proto.RegisterEnum("KindaGRPC.DTOValidationErrorCodePB", DTOValidationErrorCodePB_name, DTOValidationErrorCodePB_value)
	proto.RegisterType((*EmptyResponsePB)(nil), "KindaGRPC.EmptyResponsePB")
	proto.RegisterType((*StringResponsePB)(nil), "KindaGRPC.StringResponsePB")
	proto.RegisterType((*AuthResponsePB)(nil), "KindaGRPC.AuthResponsePB")
	proto.RegisterType((*DTOValidationResponsePB)(nil), "KindaGRPC.DTOValidationResponsePB")
	proto.RegisterType((*CollectionDTOValidationResponsePB)(nil), "KindaGRPC.CollectionDTOValidationResponsePB")
	proto.RegisterType((*GeoDistancePB)(nil), "KindaGRPC.GeoDistancePB")
}

func init() { proto.RegisterFile("kinda-outgoing.proto", fileDescriptor_cb4c0e7f06dd050b) }

var fileDescriptor_cb4c0e7f06dd050b = []byte{
	// 378 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x92, 0xcd, 0xee, 0xd2, 0x40,
	0x14, 0xc5, 0xed, 0xbf, 0xa0, 0x70, 0x05, 0x1c, 0x46, 0x0c, 0x8d, 0x2b, 0x1c, 0x37, 0x44, 0x23,
	0x0b, 0x5c, 0xb8, 0x2e, 0xed, 0x08, 0x46, 0x28, 0xcd, 0x50, 0x34, 0xb8, 0x69, 0x2a, 0x33, 0xc1,
	0x89, 0xa5, 0xd3, 0xb4, 0x83, 0x89, 0x4f, 0xe1, 0x3b, 0xf8, 0xa4, 0x66, 0x0a, 0xf2, 0xb1, 0x60,
	0xd7, 0xdf, 0x99, 0x73, 0xee, 0x3d, 0xb9, 0x29, 0xf4, 0x7e, 0xca, 0x8c, 0x27, 0xef, 0xd4, 0x41,
	0xef, 0x94, 0xcc, 0x76, 0xa3, 0xbc, 0x50, 0x5a, 0xe1, 0xe6, 0x67, 0xa3, 0x4e, 0x59, 0xe8, 0x91,
	0x2e, 0x3c, 0xa3, 0xfb, 0x5c, 0xff, 0x66, 0xa2, 0xcc, 0x55, 0x56, 0x8a, 0x70, 0x42, 0x86, 0x80,
	0x56, 0xba, 0x90, 0xd9, 0xee, 0xa2, 0xe1, 0x1e, 0xd4, 0x7f, 0x25, 0xe9, 0x41, 0x38, 0xd6, 0xc0,
	0x1a, 0x36, 0xd9, 0x11, 0x08, 0x81, 0x8e, 0x7b, 0xd0, 0x3f, 0xae, 0x7c, 0x08, 0xec, 0x52, 0x72,
	0xe7, 0xa1, 0x72, 0x99, 0x4f, 0xf2, 0xd7, 0x82, 0xbe, 0x1f, 0x2d, 0xbf, 0x24, 0xa9, 0xe4, 0x89,
	0x96, 0x2a, 0xbb, 0x72, 0x7f, 0x80, 0xda, 0x56, 0xf1, 0xe3, 0xd0, 0xce, 0xf8, 0xf5, 0xe8, 0x5c,
	0x6b, 0x74, 0x93, 0xa0, 0x45, 0xa1, 0x0a, 0x4f, 0x71, 0x11, 0x4e, 0x58, 0x15, 0xc0, 0x0e, 0x3c,
	0xe1, 0x5a, 0x05, 0xc9, 0x5e, 0x9c, 0x56, 0xfd, 0x47, 0xfc, 0x12, 0x1a, 0x5c, 0xab, 0x8f, 0x52,
	0xa4, 0xdc, 0xb1, 0xab, 0xa7, 0x33, 0x9b, 0x54, 0x9e, 0x68, 0x2d, 0x8a, 0xcc, 0xa9, 0x1d, 0x53,
	0x27, 0x24, 0x7b, 0x78, 0xe5, 0xa9, 0x34, 0x15, 0x5b, 0xb3, 0xee, 0x5e, 0xdb, 0x19, 0xb4, 0xb9,
	0x56, 0x97, 0x27, 0xc7, 0x1a, 0xd8, 0xc3, 0xa7, 0x63, 0x72, 0xaf, 0xf6, 0x25, 0xca, 0x6e, 0x83,
	0xe4, 0x2d, 0xb4, 0xa7, 0x42, 0xf9, 0xb2, 0xd4, 0x49, 0xb6, 0x35, 0xa3, 0x4d, 0xeb, 0x13, 0x55,
	0xc7, 0xb0, 0xd8, 0x99, 0xdf, 0xfc, 0xb1, 0xc0, 0xb9, 0x77, 0x0e, 0xdc, 0x82, 0x46, 0xb0, 0x8c,
	0xe2, 0x60, 0x3d, 0x9f, 0xa3, 0x47, 0xb8, 0x0d, 0x4d, 0x43, 0x74, 0x11, 0x46, 0x1b, 0x64, 0xe1,
	0x3e, 0x3c, 0x0f, 0xdd, 0x28, 0xa2, 0x2c, 0x88, 0x8d, 0xbc, 0x70, 0x23, 0x6f, 0x46, 0x7d, 0xf4,
	0x80, 0x11, 0xb4, 0x8c, 0xe0, 0x7a, 0x1e, 0x0d, 0x23, 0xea, 0x23, 0x1b, 0xf7, 0x00, 0x7d, 0x65,
	0xcb, 0x60, 0x1a, 0xbb, 0x8c, 0xb9, 0x9b, 0x78, 0xf5, 0xe9, 0x1b, 0x45, 0x35, 0xfc, 0x02, 0xba,
	0x34, 0x58, 0x2f, 0xe2, 0x1b, 0x73, 0xfd, 0xfb, 0xe3, 0xea, 0x2f, 0x7a, 0xff, 0x2f, 0x00, 0x00,
	0xff, 0xff, 0x52, 0x03, 0x36, 0xbd, 0x5d, 0x02, 0x00, 0x00,
}
