// Code generated by protoc-gen-go. DO NOT EDIT.
// source: kinda-service.proto

package KindaGRPC

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

func init() { proto.RegisterFile("kinda-service.proto", fileDescriptor_8495d10062b1f51c) }

var fileDescriptor_8495d10062b1f51c = []byte{
	// 369 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x93, 0x51, 0x4b, 0xfb, 0x30,
	0x14, 0xc5, 0xf9, 0xc3, 0x5f, 0xc5, 0x20, 0x53, 0xb2, 0x09, 0xae, 0x20, 0xf8, 0xe8, 0x8b, 0x7b,
	0xd0, 0x47, 0xf5, 0x61, 0xad, 0x3a, 0xc4, 0x4d, 0x6a, 0xa7, 0xbe, 0x67, 0xe9, 0xb5, 0x8d, 0xeb,
	0x92, 0x9a, 0xdc, 0x4e, 0xf6, 0x05, 0xfd, 0x5c, 0xd2, 0xae, 0x6e, 0x19, 0xd3, 0x75, 0xe8, 0xeb,
	0x39, 0x27, 0x3f, 0xee, 0x39, 0x10, 0x52, 0x1f, 0x0a, 0x19, 0xb2, 0x13, 0x03, 0x7a, 0x2c, 0x38,
	0xb4, 0x52, 0xad, 0x50, 0xd1, 0xed, 0xbb, 0x5c, 0xec, 0x04, 0xbe, 0xe7, 0x94, 0xbe, 0x92, 0x91,
	0x12, 0x32, 0x9a, 0xfa, 0x4e, 0xa3, 0x14, 0x33, 0xb4, 0xd4, 0xd3, 0x8f, 0x2d, 0xb2, 0x51, 0x3c,
	0xa4, 0xe7, 0xe4, 0x3f, 0xcb, 0x30, 0xa6, 0x07, 0xad, 0x19, 0xa8, 0xd5, 0xce, 0x30, 0x0e, 0xe0,
	0x2d, 0x03, 0x83, 0xbe, 0xeb, 0x34, 0x97, 0x1c, 0x93, 0x2a, 0x69, 0xc0, 0x77, 0x69, 0x97, 0xec,
	0x68, 0x88, 0x84, 0x41, 0xcd, 0x50, 0x28, 0x49, 0x8f, 0xac, 0x68, 0x60, 0x19, 0x73, 0x98, 0x63,
	0x25, 0xae, 0x47, 0x29, 0x4e, 0x16, 0x69, 0x63, 0xd0, 0xe2, 0x45, 0xf0, 0x65, 0xda, 0xb3, 0x65,
	0xac, 0x4b, 0x6b, 0x30, 0x3e, 0x94, 0xea, 0x3d, 0x81, 0x30, 0x82, 0x00, 0x5e, 0x81, 0x17, 0xd4,
	0x9f, 0x8b, 0xae, 0xa2, 0xf5, 0x89, 0x63, 0x80, 0x69, 0x1e, 0xb7, 0x39, 0x8a, 0xb1, 0xc0, 0xc9,
	0xbd, 0xc2, 0xf9, 0xa5, 0xcd, 0xe5, 0x97, 0xeb, 0x40, 0x3b, 0x64, 0x37, 0x84, 0x04, 0x10, 0xdc,
	0x44, 0xc8, 0xd0, 0x8b, 0x19, 0x2e, 0x5c, 0x37, 0x53, 0x6f, 0xc3, 0x0a, 0xd0, 0x0d, 0xa9, 0x0d,
	0x12, 0xc5, 0x87, 0x7f, 0xe5, 0x78, 0xa4, 0x66, 0x00, 0x3b, 0xa0, 0xba, 0xaa, 0x6c, 0xb6, 0x6f,
	0xa5, 0xbf, 0xc4, 0xca, 0xe1, 0xeb, 0x06, 0xb0, 0x5f, 0xac, 0xe5, 0x33, 0xcd, 0x46, 0x80, 0xa0,
	0xcd, 0xc2, 0x46, 0x96, 0x69, 0x2a, 0x68, 0x17, 0xa4, 0x16, 0x15, 0x27, 0x5d, 0x09, 0x83, 0x4c,
	0x72, 0xa0, 0x7b, 0x56, 0xfa, 0x49, 0xe4, 0x95, 0xec, 0xb2, 0x56, 0xd2, 0x77, 0xe9, 0x03, 0x69,
	0x18, 0x90, 0xe1, 0x6c, 0x81, 0x1e, 0x18, 0xc3, 0x22, 0xa0, 0x87, 0xdf, 0xcd, 0x53, 0x9a, 0x15,
	0x07, 0xf5, 0xf2, 0x7a, 0x16, 0xf2, 0x71, 0x92, 0x0a, 0x19, 0xfd, 0x6e, 0xf0, 0xe3, 0x7f, 0xf4,
	0x92, 0x90, 0x1c, 0xe7, 0xc5, 0x4a, 0x70, 0xa0, 0x75, 0x2b, 0x3b, 0x95, 0x56, 0x03, 0x06, 0x9b,
	0xc5, 0x7f, 0x3e, 0xfb, 0x0c, 0x00, 0x00, 0xff, 0xff, 0xe8, 0x43, 0x65, 0x99, 0x1c, 0x04, 0x00,
	0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// KindaClient is the client API for Kinda service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type KindaClient interface {
	//auth
	Auth(ctx context.Context, in *AuthRequestPB, opts ...grpc.CallOption) (*AuthResponsePB, error)
	Registration(ctx context.Context, in *RegistrationRequestPB, opts ...grpc.CallOption) (*EmptyResponsePB, error)
	Verification(ctx context.Context, in *VerificationRequestPB, opts ...grpc.CallOption) (*EmptyResponsePB, error)
	AcknowledgeRejection(ctx context.Context, in *AuthRequestPB, opts ...grpc.CallOption) (*EmptyResponsePB, error)
	//search
	SearchActivityNotification(ctx context.Context, in *EmptyRequestPB, opts ...grpc.CallOption) (*EmptyResponsePB, error)
	DeleteBlindChat(ctx context.Context, in *BlindChatIdPB, opts ...grpc.CallOption) (*EmptyResponsePB, error)
	BlockBlindChat(ctx context.Context, in *BlindChatIdPB, opts ...grpc.CallOption) (*EmptyResponsePB, error)
	SetGeoLocation(ctx context.Context, in *LocationPB, opts ...grpc.CallOption) (*EmptyResponsePB, error)
	SetSearchParameters(ctx context.Context, in *SearchParamsPB, opts ...grpc.CallOption) (*EmptyResponsePB, error)
	GetGeoDistance(ctx context.Context, in *UidPB, opts ...grpc.CallOption) (*GeoDistancePB, error)
	//blindChat
	SendBlindChatMessage(ctx context.Context, in *BlindChatMessagePB, opts ...grpc.CallOption) (*EmptyResponsePB, error)
	SendBlindChatTyping(ctx context.Context, opts ...grpc.CallOption) (Kinda_SendBlindChatTypingClient, error)
	SendChoice(ctx context.Context, in *ChoicePB, opts ...grpc.CallOption) (*EmptyResponsePB, error)
}

type kindaClient struct {
	cc *grpc.ClientConn
}

func NewKindaClient(cc *grpc.ClientConn) KindaClient {
	return &kindaClient{cc}
}

func (c *kindaClient) Auth(ctx context.Context, in *AuthRequestPB, opts ...grpc.CallOption) (*AuthResponsePB, error) {
	out := new(AuthResponsePB)
	err := c.cc.Invoke(ctx, "/KindaGRPC.Kinda/auth", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *kindaClient) Registration(ctx context.Context, in *RegistrationRequestPB, opts ...grpc.CallOption) (*EmptyResponsePB, error) {
	out := new(EmptyResponsePB)
	err := c.cc.Invoke(ctx, "/KindaGRPC.Kinda/registration", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *kindaClient) Verification(ctx context.Context, in *VerificationRequestPB, opts ...grpc.CallOption) (*EmptyResponsePB, error) {
	out := new(EmptyResponsePB)
	err := c.cc.Invoke(ctx, "/KindaGRPC.Kinda/verification", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *kindaClient) AcknowledgeRejection(ctx context.Context, in *AuthRequestPB, opts ...grpc.CallOption) (*EmptyResponsePB, error) {
	out := new(EmptyResponsePB)
	err := c.cc.Invoke(ctx, "/KindaGRPC.Kinda/acknowledgeRejection", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *kindaClient) SearchActivityNotification(ctx context.Context, in *EmptyRequestPB, opts ...grpc.CallOption) (*EmptyResponsePB, error) {
	out := new(EmptyResponsePB)
	err := c.cc.Invoke(ctx, "/KindaGRPC.Kinda/searchActivityNotification", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *kindaClient) DeleteBlindChat(ctx context.Context, in *BlindChatIdPB, opts ...grpc.CallOption) (*EmptyResponsePB, error) {
	out := new(EmptyResponsePB)
	err := c.cc.Invoke(ctx, "/KindaGRPC.Kinda/deleteBlindChat", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *kindaClient) BlockBlindChat(ctx context.Context, in *BlindChatIdPB, opts ...grpc.CallOption) (*EmptyResponsePB, error) {
	out := new(EmptyResponsePB)
	err := c.cc.Invoke(ctx, "/KindaGRPC.Kinda/blockBlindChat", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *kindaClient) SetGeoLocation(ctx context.Context, in *LocationPB, opts ...grpc.CallOption) (*EmptyResponsePB, error) {
	out := new(EmptyResponsePB)
	err := c.cc.Invoke(ctx, "/KindaGRPC.Kinda/setGeoLocation", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *kindaClient) SetSearchParameters(ctx context.Context, in *SearchParamsPB, opts ...grpc.CallOption) (*EmptyResponsePB, error) {
	out := new(EmptyResponsePB)
	err := c.cc.Invoke(ctx, "/KindaGRPC.Kinda/setSearchParameters", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *kindaClient) GetGeoDistance(ctx context.Context, in *UidPB, opts ...grpc.CallOption) (*GeoDistancePB, error) {
	out := new(GeoDistancePB)
	err := c.cc.Invoke(ctx, "/KindaGRPC.Kinda/getGeoDistance", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *kindaClient) SendBlindChatMessage(ctx context.Context, in *BlindChatMessagePB, opts ...grpc.CallOption) (*EmptyResponsePB, error) {
	out := new(EmptyResponsePB)
	err := c.cc.Invoke(ctx, "/KindaGRPC.Kinda/sendBlindChatMessage", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *kindaClient) SendBlindChatTyping(ctx context.Context, opts ...grpc.CallOption) (Kinda_SendBlindChatTypingClient, error) {
	stream, err := c.cc.NewStream(ctx, &_Kinda_serviceDesc.Streams[0], "/KindaGRPC.Kinda/sendBlindChatTyping", opts...)
	if err != nil {
		return nil, err
	}
	x := &kindaSendBlindChatTypingClient{stream}
	return x, nil
}

type Kinda_SendBlindChatTypingClient interface {
	Send(*BlindChatIdPB) error
	CloseAndRecv() (*EmptyResponsePB, error)
	grpc.ClientStream
}

type kindaSendBlindChatTypingClient struct {
	grpc.ClientStream
}

func (x *kindaSendBlindChatTypingClient) Send(m *BlindChatIdPB) error {
	return x.ClientStream.SendMsg(m)
}

func (x *kindaSendBlindChatTypingClient) CloseAndRecv() (*EmptyResponsePB, error) {
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	m := new(EmptyResponsePB)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *kindaClient) SendChoice(ctx context.Context, in *ChoicePB, opts ...grpc.CallOption) (*EmptyResponsePB, error) {
	out := new(EmptyResponsePB)
	err := c.cc.Invoke(ctx, "/KindaGRPC.Kinda/sendChoice", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// KindaServer is the server API for Kinda service.
type KindaServer interface {
	//auth
	Auth(context.Context, *AuthRequestPB) (*AuthResponsePB, error)
	Registration(context.Context, *RegistrationRequestPB) (*EmptyResponsePB, error)
	Verification(context.Context, *VerificationRequestPB) (*EmptyResponsePB, error)
	AcknowledgeRejection(context.Context, *AuthRequestPB) (*EmptyResponsePB, error)
	//search
	SearchActivityNotification(context.Context, *EmptyRequestPB) (*EmptyResponsePB, error)
	DeleteBlindChat(context.Context, *BlindChatIdPB) (*EmptyResponsePB, error)
	BlockBlindChat(context.Context, *BlindChatIdPB) (*EmptyResponsePB, error)
	SetGeoLocation(context.Context, *LocationPB) (*EmptyResponsePB, error)
	SetSearchParameters(context.Context, *SearchParamsPB) (*EmptyResponsePB, error)
	GetGeoDistance(context.Context, *UidPB) (*GeoDistancePB, error)
	//blindChat
	SendBlindChatMessage(context.Context, *BlindChatMessagePB) (*EmptyResponsePB, error)
	SendBlindChatTyping(Kinda_SendBlindChatTypingServer) error
	SendChoice(context.Context, *ChoicePB) (*EmptyResponsePB, error)
}

// UnimplementedKindaServer can be embedded to have forward compatible implementations.
type UnimplementedKindaServer struct {
}

func (*UnimplementedKindaServer) Auth(ctx context.Context, req *AuthRequestPB) (*AuthResponsePB, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Auth not implemented")
}
func (*UnimplementedKindaServer) Registration(ctx context.Context, req *RegistrationRequestPB) (*EmptyResponsePB, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Registration not implemented")
}
func (*UnimplementedKindaServer) Verification(ctx context.Context, req *VerificationRequestPB) (*EmptyResponsePB, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Verification not implemented")
}
func (*UnimplementedKindaServer) AcknowledgeRejection(ctx context.Context, req *AuthRequestPB) (*EmptyResponsePB, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AcknowledgeRejection not implemented")
}
func (*UnimplementedKindaServer) SearchActivityNotification(ctx context.Context, req *EmptyRequestPB) (*EmptyResponsePB, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SearchActivityNotification not implemented")
}
func (*UnimplementedKindaServer) DeleteBlindChat(ctx context.Context, req *BlindChatIdPB) (*EmptyResponsePB, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteBlindChat not implemented")
}
func (*UnimplementedKindaServer) BlockBlindChat(ctx context.Context, req *BlindChatIdPB) (*EmptyResponsePB, error) {
	return nil, status.Errorf(codes.Unimplemented, "method BlockBlindChat not implemented")
}
func (*UnimplementedKindaServer) SetGeoLocation(ctx context.Context, req *LocationPB) (*EmptyResponsePB, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SetGeoLocation not implemented")
}
func (*UnimplementedKindaServer) SetSearchParameters(ctx context.Context, req *SearchParamsPB) (*EmptyResponsePB, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SetSearchParameters not implemented")
}
func (*UnimplementedKindaServer) GetGeoDistance(ctx context.Context, req *UidPB) (*GeoDistancePB, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetGeoDistance not implemented")
}
func (*UnimplementedKindaServer) SendBlindChatMessage(ctx context.Context, req *BlindChatMessagePB) (*EmptyResponsePB, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SendBlindChatMessage not implemented")
}
func (*UnimplementedKindaServer) SendBlindChatTyping(srv Kinda_SendBlindChatTypingServer) error {
	return status.Errorf(codes.Unimplemented, "method SendBlindChatTyping not implemented")
}
func (*UnimplementedKindaServer) SendChoice(ctx context.Context, req *ChoicePB) (*EmptyResponsePB, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SendChoice not implemented")
}

func RegisterKindaServer(s *grpc.Server, srv KindaServer) {
	s.RegisterService(&_Kinda_serviceDesc, srv)
}

func _Kinda_Auth_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AuthRequestPB)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KindaServer).Auth(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/KindaGRPC.Kinda/Auth",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KindaServer).Auth(ctx, req.(*AuthRequestPB))
	}
	return interceptor(ctx, in, info, handler)
}

func _Kinda_Registration_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegistrationRequestPB)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KindaServer).Registration(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/KindaGRPC.Kinda/Registration",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KindaServer).Registration(ctx, req.(*RegistrationRequestPB))
	}
	return interceptor(ctx, in, info, handler)
}

func _Kinda_Verification_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(VerificationRequestPB)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KindaServer).Verification(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/KindaGRPC.Kinda/Verification",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KindaServer).Verification(ctx, req.(*VerificationRequestPB))
	}
	return interceptor(ctx, in, info, handler)
}

func _Kinda_AcknowledgeRejection_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AuthRequestPB)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KindaServer).AcknowledgeRejection(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/KindaGRPC.Kinda/AcknowledgeRejection",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KindaServer).AcknowledgeRejection(ctx, req.(*AuthRequestPB))
	}
	return interceptor(ctx, in, info, handler)
}

func _Kinda_SearchActivityNotification_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EmptyRequestPB)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KindaServer).SearchActivityNotification(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/KindaGRPC.Kinda/SearchActivityNotification",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KindaServer).SearchActivityNotification(ctx, req.(*EmptyRequestPB))
	}
	return interceptor(ctx, in, info, handler)
}

func _Kinda_DeleteBlindChat_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BlindChatIdPB)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KindaServer).DeleteBlindChat(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/KindaGRPC.Kinda/DeleteBlindChat",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KindaServer).DeleteBlindChat(ctx, req.(*BlindChatIdPB))
	}
	return interceptor(ctx, in, info, handler)
}

func _Kinda_BlockBlindChat_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BlindChatIdPB)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KindaServer).BlockBlindChat(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/KindaGRPC.Kinda/BlockBlindChat",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KindaServer).BlockBlindChat(ctx, req.(*BlindChatIdPB))
	}
	return interceptor(ctx, in, info, handler)
}

func _Kinda_SetGeoLocation_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LocationPB)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KindaServer).SetGeoLocation(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/KindaGRPC.Kinda/SetGeoLocation",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KindaServer).SetGeoLocation(ctx, req.(*LocationPB))
	}
	return interceptor(ctx, in, info, handler)
}

func _Kinda_SetSearchParameters_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SearchParamsPB)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KindaServer).SetSearchParameters(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/KindaGRPC.Kinda/SetSearchParameters",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KindaServer).SetSearchParameters(ctx, req.(*SearchParamsPB))
	}
	return interceptor(ctx, in, info, handler)
}

func _Kinda_GetGeoDistance_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UidPB)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KindaServer).GetGeoDistance(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/KindaGRPC.Kinda/GetGeoDistance",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KindaServer).GetGeoDistance(ctx, req.(*UidPB))
	}
	return interceptor(ctx, in, info, handler)
}

func _Kinda_SendBlindChatMessage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BlindChatMessagePB)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KindaServer).SendBlindChatMessage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/KindaGRPC.Kinda/SendBlindChatMessage",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KindaServer).SendBlindChatMessage(ctx, req.(*BlindChatMessagePB))
	}
	return interceptor(ctx, in, info, handler)
}

func _Kinda_SendBlindChatTyping_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(KindaServer).SendBlindChatTyping(&kindaSendBlindChatTypingServer{stream})
}

type Kinda_SendBlindChatTypingServer interface {
	SendAndClose(*EmptyResponsePB) error
	Recv() (*BlindChatIdPB, error)
	grpc.ServerStream
}

type kindaSendBlindChatTypingServer struct {
	grpc.ServerStream
}

func (x *kindaSendBlindChatTypingServer) SendAndClose(m *EmptyResponsePB) error {
	return x.ServerStream.SendMsg(m)
}

func (x *kindaSendBlindChatTypingServer) Recv() (*BlindChatIdPB, error) {
	m := new(BlindChatIdPB)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func _Kinda_SendChoice_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ChoicePB)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KindaServer).SendChoice(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/KindaGRPC.Kinda/SendChoice",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KindaServer).SendChoice(ctx, req.(*ChoicePB))
	}
	return interceptor(ctx, in, info, handler)
}

var _Kinda_serviceDesc = grpc.ServiceDesc{
	ServiceName: "KindaGRPC.Kinda",
	HandlerType: (*KindaServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "auth",
			Handler:    _Kinda_Auth_Handler,
		},
		{
			MethodName: "registration",
			Handler:    _Kinda_Registration_Handler,
		},
		{
			MethodName: "verification",
			Handler:    _Kinda_Verification_Handler,
		},
		{
			MethodName: "acknowledgeRejection",
			Handler:    _Kinda_AcknowledgeRejection_Handler,
		},
		{
			MethodName: "searchActivityNotification",
			Handler:    _Kinda_SearchActivityNotification_Handler,
		},
		{
			MethodName: "deleteBlindChat",
			Handler:    _Kinda_DeleteBlindChat_Handler,
		},
		{
			MethodName: "blockBlindChat",
			Handler:    _Kinda_BlockBlindChat_Handler,
		},
		{
			MethodName: "setGeoLocation",
			Handler:    _Kinda_SetGeoLocation_Handler,
		},
		{
			MethodName: "setSearchParameters",
			Handler:    _Kinda_SetSearchParameters_Handler,
		},
		{
			MethodName: "getGeoDistance",
			Handler:    _Kinda_GetGeoDistance_Handler,
		},
		{
			MethodName: "sendBlindChatMessage",
			Handler:    _Kinda_SendBlindChatMessage_Handler,
		},
		{
			MethodName: "sendChoice",
			Handler:    _Kinda_SendChoice_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "sendBlindChatTyping",
			Handler:       _Kinda_SendBlindChatTyping_Handler,
			ClientStreams: true,
		},
	},
	Metadata: "kinda-service.proto",
}
