// Code generated by protoc-gen-go. DO NOT EDIT.
// source: kinda-outgoing.proto

package KindaGRPC

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type DTOValidationErrorCodePB int32

const (
	DTOValidationErrorCodePB_NOT_NULL               DTOValidationErrorCodePB = 0
	DTOValidationErrorCodePB_NOT_EMPTY              DTOValidationErrorCodePB = 1
	DTOValidationErrorCodePB_PATTERN_NOT_MATCHED    DTOValidationErrorCodePB = 2
	DTOValidationErrorCodePB_NOT_ACCEPTED           DTOValidationErrorCodePB = 3
	DTOValidationErrorCodePB_WRONG_ARRAY_SIZE       DTOValidationErrorCodePB = 4
	DTOValidationErrorCodePB_WRONG_ARRAY_UNIQUENESS DTOValidationErrorCodePB = 5
	DTOValidationErrorCodePB_ENUM_NOT_ACCEPTED      DTOValidationErrorCodePB = 6
)

var DTOValidationErrorCodePB_name = map[int32]string{
	0: "NOT_NULL",
	1: "NOT_EMPTY",
	2: "PATTERN_NOT_MATCHED",
	3: "NOT_ACCEPTED",
	4: "WRONG_ARRAY_SIZE",
	5: "WRONG_ARRAY_UNIQUENESS",
	6: "ENUM_NOT_ACCEPTED",
}

var DTOValidationErrorCodePB_value = map[string]int32{
	"NOT_NULL":               0,
	"NOT_EMPTY":              1,
	"PATTERN_NOT_MATCHED":    2,
	"NOT_ACCEPTED":           3,
	"WRONG_ARRAY_SIZE":       4,
	"WRONG_ARRAY_UNIQUENESS": 5,
	"ENUM_NOT_ACCEPTED":      6,
}

func (x DTOValidationErrorCodePB) String() string {
	return proto.EnumName(DTOValidationErrorCodePB_name, int32(x))
}

func (DTOValidationErrorCodePB) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_cb4c0e7f06dd050b, []int{0}
}

type EmptyResponsePB struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EmptyResponsePB) Reset()         { *m = EmptyResponsePB{} }
func (m *EmptyResponsePB) String() string { return proto.CompactTextString(m) }
func (*EmptyResponsePB) ProtoMessage()    {}
func (*EmptyResponsePB) Descriptor() ([]byte, []int) {
	return fileDescriptor_cb4c0e7f06dd050b, []int{0}
}

func (m *EmptyResponsePB) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EmptyResponsePB.Unmarshal(m, b)
}
func (m *EmptyResponsePB) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EmptyResponsePB.Marshal(b, m, deterministic)
}
func (m *EmptyResponsePB) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EmptyResponsePB.Merge(m, src)
}
func (m *EmptyResponsePB) XXX_Size() int {
	return xxx_messageInfo_EmptyResponsePB.Size(m)
}
func (m *EmptyResponsePB) XXX_DiscardUnknown() {
	xxx_messageInfo_EmptyResponsePB.DiscardUnknown(m)
}

var xxx_messageInfo_EmptyResponsePB proto.InternalMessageInfo

type StringResponsePB struct {
	Value                string   `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StringResponsePB) Reset()         { *m = StringResponsePB{} }
func (m *StringResponsePB) String() string { return proto.CompactTextString(m) }
func (*StringResponsePB) ProtoMessage()    {}
func (*StringResponsePB) Descriptor() ([]byte, []int) {
	return fileDescriptor_cb4c0e7f06dd050b, []int{1}
}

func (m *StringResponsePB) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StringResponsePB.Unmarshal(m, b)
}
func (m *StringResponsePB) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StringResponsePB.Marshal(b, m, deterministic)
}
func (m *StringResponsePB) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StringResponsePB.Merge(m, src)
}
func (m *StringResponsePB) XXX_Size() int {
	return xxx_messageInfo_StringResponsePB.Size(m)
}
func (m *StringResponsePB) XXX_DiscardUnknown() {
	xxx_messageInfo_StringResponsePB.DiscardUnknown(m)
}

var xxx_messageInfo_StringResponsePB proto.InternalMessageInfo

func (m *StringResponsePB) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

type BooleanResponsePB struct {
	Value                bool     `protobuf:"varint,1,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BooleanResponsePB) Reset()         { *m = BooleanResponsePB{} }
func (m *BooleanResponsePB) String() string { return proto.CompactTextString(m) }
func (*BooleanResponsePB) ProtoMessage()    {}
func (*BooleanResponsePB) Descriptor() ([]byte, []int) {
	return fileDescriptor_cb4c0e7f06dd050b, []int{2}
}

func (m *BooleanResponsePB) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BooleanResponsePB.Unmarshal(m, b)
}
func (m *BooleanResponsePB) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BooleanResponsePB.Marshal(b, m, deterministic)
}
func (m *BooleanResponsePB) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BooleanResponsePB.Merge(m, src)
}
func (m *BooleanResponsePB) XXX_Size() int {
	return xxx_messageInfo_BooleanResponsePB.Size(m)
}
func (m *BooleanResponsePB) XXX_DiscardUnknown() {
	xxx_messageInfo_BooleanResponsePB.DiscardUnknown(m)
}

var xxx_messageInfo_BooleanResponsePB proto.InternalMessageInfo

func (m *BooleanResponsePB) GetValue() bool {
	if m != nil {
		return m.Value
	}
	return false
}

// [START authorization]
type AuthResponsePB struct {
	Sid                  string   `protobuf:"bytes,2,opt,name=sid,proto3" json:"sid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AuthResponsePB) Reset()         { *m = AuthResponsePB{} }
func (m *AuthResponsePB) String() string { return proto.CompactTextString(m) }
func (*AuthResponsePB) ProtoMessage()    {}
func (*AuthResponsePB) Descriptor() ([]byte, []int) {
	return fileDescriptor_cb4c0e7f06dd050b, []int{3}
}

func (m *AuthResponsePB) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AuthResponsePB.Unmarshal(m, b)
}
func (m *AuthResponsePB) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AuthResponsePB.Marshal(b, m, deterministic)
}
func (m *AuthResponsePB) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AuthResponsePB.Merge(m, src)
}
func (m *AuthResponsePB) XXX_Size() int {
	return xxx_messageInfo_AuthResponsePB.Size(m)
}
func (m *AuthResponsePB) XXX_DiscardUnknown() {
	xxx_messageInfo_AuthResponsePB.DiscardUnknown(m)
}

var xxx_messageInfo_AuthResponsePB proto.InternalMessageInfo

func (m *AuthResponsePB) GetSid() string {
	if m != nil {
		return m.Sid
	}
	return ""
}

type DTOValidationResponsePB struct {
	Code                 DTOValidationErrorCodePB `protobuf:"varint,1,opt,name=code,proto3,enum=KindaGRPC.DTOValidationErrorCodePB" json:"code,omitempty"`
	DtoName              string                   `protobuf:"bytes,2,opt,name=dtoName,proto3" json:"dtoName,omitempty"`
	DtoField             string                   `protobuf:"bytes,3,opt,name=dtoField,proto3" json:"dtoField,omitempty"`
	Pattern              string                   `protobuf:"bytes,4,opt,name=pattern,proto3" json:"pattern,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                 `json:"-"`
	XXX_unrecognized     []byte                   `json:"-"`
	XXX_sizecache        int32                    `json:"-"`
}

func (m *DTOValidationResponsePB) Reset()         { *m = DTOValidationResponsePB{} }
func (m *DTOValidationResponsePB) String() string { return proto.CompactTextString(m) }
func (*DTOValidationResponsePB) ProtoMessage()    {}
func (*DTOValidationResponsePB) Descriptor() ([]byte, []int) {
	return fileDescriptor_cb4c0e7f06dd050b, []int{4}
}

func (m *DTOValidationResponsePB) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DTOValidationResponsePB.Unmarshal(m, b)
}
func (m *DTOValidationResponsePB) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DTOValidationResponsePB.Marshal(b, m, deterministic)
}
func (m *DTOValidationResponsePB) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DTOValidationResponsePB.Merge(m, src)
}
func (m *DTOValidationResponsePB) XXX_Size() int {
	return xxx_messageInfo_DTOValidationResponsePB.Size(m)
}
func (m *DTOValidationResponsePB) XXX_DiscardUnknown() {
	xxx_messageInfo_DTOValidationResponsePB.DiscardUnknown(m)
}

var xxx_messageInfo_DTOValidationResponsePB proto.InternalMessageInfo

func (m *DTOValidationResponsePB) GetCode() DTOValidationErrorCodePB {
	if m != nil {
		return m.Code
	}
	return DTOValidationErrorCodePB_NOT_NULL
}

func (m *DTOValidationResponsePB) GetDtoName() string {
	if m != nil {
		return m.DtoName
	}
	return ""
}

func (m *DTOValidationResponsePB) GetDtoField() string {
	if m != nil {
		return m.DtoField
	}
	return ""
}

func (m *DTOValidationResponsePB) GetPattern() string {
	if m != nil {
		return m.Pattern
	}
	return ""
}

type CollectionDTOValidationResponsePB struct {
	DtoValidation        []*DTOValidationResponsePB `protobuf:"bytes,1,rep,name=dtoValidation,proto3" json:"dtoValidation,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                   `json:"-"`
	XXX_unrecognized     []byte                     `json:"-"`
	XXX_sizecache        int32                      `json:"-"`
}

func (m *CollectionDTOValidationResponsePB) Reset()         { *m = CollectionDTOValidationResponsePB{} }
func (m *CollectionDTOValidationResponsePB) String() string { return proto.CompactTextString(m) }
func (*CollectionDTOValidationResponsePB) ProtoMessage()    {}
func (*CollectionDTOValidationResponsePB) Descriptor() ([]byte, []int) {
	return fileDescriptor_cb4c0e7f06dd050b, []int{5}
}

func (m *CollectionDTOValidationResponsePB) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CollectionDTOValidationResponsePB.Unmarshal(m, b)
}
func (m *CollectionDTOValidationResponsePB) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CollectionDTOValidationResponsePB.Marshal(b, m, deterministic)
}
func (m *CollectionDTOValidationResponsePB) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CollectionDTOValidationResponsePB.Merge(m, src)
}
func (m *CollectionDTOValidationResponsePB) XXX_Size() int {
	return xxx_messageInfo_CollectionDTOValidationResponsePB.Size(m)
}
func (m *CollectionDTOValidationResponsePB) XXX_DiscardUnknown() {
	xxx_messageInfo_CollectionDTOValidationResponsePB.DiscardUnknown(m)
}

var xxx_messageInfo_CollectionDTOValidationResponsePB proto.InternalMessageInfo

func (m *CollectionDTOValidationResponsePB) GetDtoValidation() []*DTOValidationResponsePB {
	if m != nil {
		return m.DtoValidation
	}
	return nil
}

type GeoDistancePB struct {
	Distance             float64  `protobuf:"fixed64,1,opt,name=distance,proto3" json:"distance,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GeoDistancePB) Reset()         { *m = GeoDistancePB{} }
func (m *GeoDistancePB) String() string { return proto.CompactTextString(m) }
func (*GeoDistancePB) ProtoMessage()    {}
func (*GeoDistancePB) Descriptor() ([]byte, []int) {
	return fileDescriptor_cb4c0e7f06dd050b, []int{6}
}

func (m *GeoDistancePB) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GeoDistancePB.Unmarshal(m, b)
}
func (m *GeoDistancePB) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GeoDistancePB.Marshal(b, m, deterministic)
}
func (m *GeoDistancePB) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GeoDistancePB.Merge(m, src)
}
func (m *GeoDistancePB) XXX_Size() int {
	return xxx_messageInfo_GeoDistancePB.Size(m)
}
func (m *GeoDistancePB) XXX_DiscardUnknown() {
	xxx_messageInfo_GeoDistancePB.DiscardUnknown(m)
}

var xxx_messageInfo_GeoDistancePB proto.InternalMessageInfo

func (m *GeoDistancePB) GetDistance() float64 {
	if m != nil {
		return m.Distance
	}
	return 0
}

type VersionPB struct {
	Version              string   `protobuf:"bytes,1,opt,name=version,proto3" json:"version,omitempty"`
	GooglePlayStoreLink  string   `protobuf:"bytes,2,opt,name=googlePlayStoreLink,proto3" json:"googlePlayStoreLink,omitempty"`
	AppleStoreLink       string   `protobuf:"bytes,3,opt,name=appleStoreLink,proto3" json:"appleStoreLink,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *VersionPB) Reset()         { *m = VersionPB{} }
func (m *VersionPB) String() string { return proto.CompactTextString(m) }
func (*VersionPB) ProtoMessage()    {}
func (*VersionPB) Descriptor() ([]byte, []int) {
	return fileDescriptor_cb4c0e7f06dd050b, []int{7}
}

func (m *VersionPB) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_VersionPB.Unmarshal(m, b)
}
func (m *VersionPB) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_VersionPB.Marshal(b, m, deterministic)
}
func (m *VersionPB) XXX_Merge(src proto.Message) {
	xxx_messageInfo_VersionPB.Merge(m, src)
}
func (m *VersionPB) XXX_Size() int {
	return xxx_messageInfo_VersionPB.Size(m)
}
func (m *VersionPB) XXX_DiscardUnknown() {
	xxx_messageInfo_VersionPB.DiscardUnknown(m)
}

var xxx_messageInfo_VersionPB proto.InternalMessageInfo

func (m *VersionPB) GetVersion() string {
	if m != nil {
		return m.Version
	}
	return ""
}

func (m *VersionPB) GetGooglePlayStoreLink() string {
	if m != nil {
		return m.GooglePlayStoreLink
	}
	return ""
}

func (m *VersionPB) GetAppleStoreLink() string {
	if m != nil {
		return m.AppleStoreLink
	}
	return ""
}

func init() {
	proto.RegisterEnum("KindaGRPC.DTOValidationErrorCodePB", DTOValidationErrorCodePB_name, DTOValidationErrorCodePB_value)
	proto.RegisterType((*EmptyResponsePB)(nil), "KindaGRPC.EmptyResponsePB")
	proto.RegisterType((*StringResponsePB)(nil), "KindaGRPC.StringResponsePB")
	proto.RegisterType((*BooleanResponsePB)(nil), "KindaGRPC.BooleanResponsePB")
	proto.RegisterType((*AuthResponsePB)(nil), "KindaGRPC.AuthResponsePB")
	proto.RegisterType((*DTOValidationResponsePB)(nil), "KindaGRPC.DTOValidationResponsePB")
	proto.RegisterType((*CollectionDTOValidationResponsePB)(nil), "KindaGRPC.CollectionDTOValidationResponsePB")
	proto.RegisterType((*GeoDistancePB)(nil), "KindaGRPC.GeoDistancePB")
	proto.RegisterType((*VersionPB)(nil), "KindaGRPC.VersionPB")
}

func init() { proto.RegisterFile("kinda-outgoing.proto", fileDescriptor_cb4c0e7f06dd050b) }

var fileDescriptor_cb4c0e7f06dd050b = []byte{
	// 466 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x93, 0x4f, 0x6f, 0xd3, 0x4c,
	0x10, 0xc6, 0x5f, 0x37, 0x69, 0xdf, 0x64, 0x68, 0xc2, 0x66, 0x1b, 0xa8, 0xd5, 0x53, 0x31, 0x12,
	0x0a, 0x20, 0x22, 0x54, 0x0e, 0x9c, 0x1d, 0x67, 0x49, 0x2b, 0x12, 0xc7, 0x6c, 0x9c, 0xa2, 0x72,
	0x89, 0x96, 0x78, 0x15, 0x56, 0x75, 0x3c, 0x96, 0xb3, 0xa9, 0xd4, 0x13, 0xdf, 0x85, 0x2b, 0x5f,
	0x12, 0x6d, 0xec, 0xfc, 0x43, 0xe4, 0xe6, 0xdf, 0x33, 0xf3, 0x3c, 0x3b, 0x3b, 0x2b, 0x43, 0xf3,
	0x5e, 0x25, 0x91, 0x78, 0x87, 0x4b, 0x3d, 0x43, 0x95, 0xcc, 0xda, 0x69, 0x86, 0x1a, 0x69, 0xf5,
	0xb3, 0x51, 0x7b, 0x3c, 0xf0, 0x9c, 0x06, 0x3c, 0x65, 0xf3, 0x54, 0x3f, 0x72, 0xb9, 0x48, 0x31,
	0x59, 0xc8, 0xa0, 0xe3, 0xb4, 0x80, 0x8c, 0x74, 0xa6, 0x92, 0xd9, 0x56, 0xa3, 0x4d, 0x38, 0x7e,
	0x10, 0xf1, 0x52, 0xda, 0xd6, 0xa5, 0xd5, 0xaa, 0xf2, 0x1c, 0x9c, 0xd7, 0xd0, 0xe8, 0x20, 0xc6,
	0x52, 0x24, 0x87, 0x5a, 0x2b, 0xeb, 0x56, 0x07, 0xea, 0xee, 0x52, 0xff, 0xd8, 0xe9, 0x23, 0x50,
	0x5a, 0xa8, 0xc8, 0x3e, 0x5a, 0x05, 0x9a, 0x4f, 0xe7, 0x97, 0x05, 0xe7, 0xdd, 0x70, 0x78, 0x2b,
	0x62, 0x15, 0x09, 0xad, 0x70, 0x37, 0xf5, 0x23, 0x94, 0xa7, 0x18, 0xe5, 0xa1, 0xf5, 0xab, 0x97,
	0xed, 0xcd, 0x0d, 0xda, 0x7b, 0x0e, 0x96, 0x65, 0x98, 0x79, 0x18, 0xc9, 0xa0, 0xc3, 0x57, 0x06,
	0x6a, 0xc3, 0xff, 0x91, 0x46, 0x5f, 0xcc, 0x65, 0x71, 0xd4, 0x1a, 0xe9, 0x05, 0x54, 0x22, 0x8d,
	0x9f, 0x94, 0x8c, 0x23, 0xbb, 0xb4, 0x2a, 0x6d, 0xd8, 0xb8, 0x52, 0xa1, 0xb5, 0xcc, 0x12, 0xbb,
	0x9c, 0xbb, 0x0a, 0x74, 0xe6, 0xf0, 0xc2, 0xc3, 0x38, 0x96, 0x53, 0x73, 0xdc, 0xa1, 0x69, 0xaf,
	0xa1, 0x16, 0x69, 0xdc, 0x96, 0x6c, 0xeb, 0xb2, 0xd4, 0x7a, 0x72, 0xe5, 0x1c, 0x1a, 0x7b, 0x6b,
	0xe5, 0xfb, 0x46, 0xe7, 0x2d, 0xd4, 0x7a, 0x12, 0xbb, 0x6a, 0xa1, 0x45, 0x32, 0x35, 0xd1, 0x66,
	0xea, 0x82, 0x56, 0xcb, 0xb0, 0xf8, 0x86, 0x9d, 0x9f, 0x50, 0xbd, 0x95, 0xd9, 0x42, 0x61, 0x12,
	0x74, 0xcc, 0x15, 0x1e, 0x72, 0x28, 0x1e, 0x6d, 0x8d, 0xf4, 0x3d, 0x9c, 0xcd, 0x10, 0x67, 0xb1,
	0x0c, 0x62, 0xf1, 0x38, 0xd2, 0x98, 0xc9, 0xbe, 0x4a, 0xee, 0x8b, 0xf5, 0xfc, 0xab, 0x44, 0x5f,
	0x41, 0x5d, 0xa4, 0x69, 0x2c, 0xb7, 0xcd, 0xf9, 0xc2, 0xfe, 0x52, 0xdf, 0xfc, 0xb6, 0xc0, 0x3e,
	0xf4, 0x1e, 0xf4, 0x14, 0x2a, 0xfe, 0x30, 0x9c, 0xf8, 0xe3, 0x7e, 0x9f, 0xfc, 0x47, 0x6b, 0x50,
	0x35, 0xc4, 0x06, 0x41, 0x78, 0x47, 0x2c, 0x7a, 0x0e, 0x67, 0x81, 0x1b, 0x86, 0x8c, 0xfb, 0x13,
	0x23, 0x0f, 0xdc, 0xd0, 0xbb, 0x66, 0x5d, 0x72, 0x44, 0x09, 0x9c, 0x1a, 0xc1, 0xf5, 0x3c, 0x16,
	0x84, 0xac, 0x4b, 0x4a, 0xb4, 0x09, 0xe4, 0x2b, 0x1f, 0xfa, 0xbd, 0x89, 0xcb, 0xb9, 0x7b, 0x37,
	0x19, 0xdd, 0x7c, 0x63, 0xa4, 0x4c, 0x2f, 0xe0, 0xf9, 0xae, 0x3a, 0xf6, 0x6f, 0xbe, 0x8c, 0x99,
	0xcf, 0x46, 0x23, 0x72, 0x4c, 0x9f, 0x41, 0x83, 0xf9, 0xe3, 0xc1, 0x64, 0x2f, 0xe8, 0xe4, 0xfb,
	0xc9, 0xea, 0x6f, 0xf8, 0xf0, 0x27, 0x00, 0x00, 0xff, 0xff, 0x57, 0x41, 0xd2, 0x05, 0x25, 0x03,
	0x00, 0x00,
}
