// Code generated by protoc-gen-go. DO NOT EDIT.
// source: ingoingPB.proto

package IngoingPB

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// [START messages]
type SupportedAuthProvidersPB int32

const (
	SupportedAuthProvidersPB_FB SupportedAuthProvidersPB = 0
)

var SupportedAuthProvidersPB_name = map[int32]string{
	0: "FB",
}

var SupportedAuthProvidersPB_value = map[string]int32{
	"FB": 0,
}

func (x SupportedAuthProvidersPB) String() string {
	return proto.EnumName(SupportedAuthProvidersPB_name, int32(x))
}

func (SupportedAuthProvidersPB) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_fdbaea811b75d51c, []int{0}
}

type AuthPB struct {
	Token                string                   `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	Provider             SupportedAuthProvidersPB `protobuf:"varint,2,opt,name=provider,proto3,enum=IngoingPB.SupportedAuthProvidersPB" json:"provider,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                 `json:"-"`
	XXX_unrecognized     []byte                   `json:"-"`
	XXX_sizecache        int32                    `json:"-"`
}

func (m *AuthPB) Reset()         { *m = AuthPB{} }
func (m *AuthPB) String() string { return proto.CompactTextString(m) }
func (*AuthPB) ProtoMessage()    {}
func (*AuthPB) Descriptor() ([]byte, []int) {
	return fileDescriptor_fdbaea811b75d51c, []int{0}
}

func (m *AuthPB) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AuthPB.Unmarshal(m, b)
}
func (m *AuthPB) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AuthPB.Marshal(b, m, deterministic)
}
func (m *AuthPB) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AuthPB.Merge(m, src)
}
func (m *AuthPB) XXX_Size() int {
	return xxx_messageInfo_AuthPB.Size(m)
}
func (m *AuthPB) XXX_DiscardUnknown() {
	xxx_messageInfo_AuthPB.DiscardUnknown(m)
}

var xxx_messageInfo_AuthPB proto.InternalMessageInfo

func (m *AuthPB) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

func (m *AuthPB) GetProvider() SupportedAuthProvidersPB {
	if m != nil {
		return m.Provider
	}
	return SupportedAuthProvidersPB_FB
}

type RegistrationPB struct {
	AuthPB               *AuthPB  `protobuf:"bytes,1,opt,name=authPB,proto3" json:"authPB,omitempty"`
	PersonalityTest      []int32  `protobuf:"varint,2,rep,packed,name=personalityTest,proto3" json:"personalityTest,omitempty"`
	Lat                  float64  `protobuf:"fixed64,3,opt,name=lat,proto3" json:"lat,omitempty"`
	Lon                  float64  `protobuf:"fixed64,4,opt,name=lon,proto3" json:"lon,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RegistrationPB) Reset()         { *m = RegistrationPB{} }
func (m *RegistrationPB) String() string { return proto.CompactTextString(m) }
func (*RegistrationPB) ProtoMessage()    {}
func (*RegistrationPB) Descriptor() ([]byte, []int) {
	return fileDescriptor_fdbaea811b75d51c, []int{1}
}

func (m *RegistrationPB) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RegistrationPB.Unmarshal(m, b)
}
func (m *RegistrationPB) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RegistrationPB.Marshal(b, m, deterministic)
}
func (m *RegistrationPB) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RegistrationPB.Merge(m, src)
}
func (m *RegistrationPB) XXX_Size() int {
	return xxx_messageInfo_RegistrationPB.Size(m)
}
func (m *RegistrationPB) XXX_DiscardUnknown() {
	xxx_messageInfo_RegistrationPB.DiscardUnknown(m)
}

var xxx_messageInfo_RegistrationPB proto.InternalMessageInfo

func (m *RegistrationPB) GetAuthPB() *AuthPB {
	if m != nil {
		return m.AuthPB
	}
	return nil
}

func (m *RegistrationPB) GetPersonalityTest() []int32 {
	if m != nil {
		return m.PersonalityTest
	}
	return nil
}

func (m *RegistrationPB) GetLat() float64 {
	if m != nil {
		return m.Lat
	}
	return 0
}

func (m *RegistrationPB) GetLon() float64 {
	if m != nil {
		return m.Lon
	}
	return 0
}

func init() {
	proto.RegisterEnum("IngoingPB.SupportedAuthProvidersPB", SupportedAuthProvidersPB_name, SupportedAuthProvidersPB_value)
	proto.RegisterType((*AuthPB)(nil), "IngoingPB.AuthPB")
	proto.RegisterType((*RegistrationPB)(nil), "IngoingPB.RegistrationPB")
}

func init() { proto.RegisterFile("ingoingPB.proto", fileDescriptor_fdbaea811b75d51c) }

var fileDescriptor_fdbaea811b75d51c = []byte{
	// 228 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x50, 0xcd, 0x4a, 0xc4, 0x30,
	0x10, 0x36, 0xad, 0x5b, 0xdc, 0x11, 0x76, 0x6b, 0xf0, 0x90, 0x63, 0xa9, 0x97, 0x28, 0xd2, 0xc3,
	0xfa, 0x00, 0x62, 0x0e, 0x82, 0xb7, 0x10, 0xbd, 0x4b, 0x64, 0x43, 0x0d, 0x2e, 0x99, 0x90, 0xcc,
	0x0a, 0x3e, 0x84, 0xef, 0x2c, 0x66, 0x6b, 0x11, 0xc1, 0xdb, 0xcc, 0x37, 0xdf, 0x1f, 0x03, 0x6b,
	0x1f, 0x46, 0xf4, 0x61, 0xd4, 0x6a, 0x88, 0x09, 0x09, 0xf9, 0xf2, 0xe1, 0x07, 0xe8, 0x9f, 0xa1,
	0xb9, 0xdb, 0xd3, 0xab, 0x56, 0xfc, 0x1c, 0x16, 0x84, 0x6f, 0x2e, 0x08, 0xd6, 0x31, 0xb9, 0x34,
	0x87, 0x85, 0xdf, 0xc2, 0x49, 0x4c, 0xf8, 0xee, 0xb7, 0x2e, 0x89, 0xaa, 0x63, 0x72, 0xb5, 0xb9,
	0x18, 0x66, 0xf5, 0xf0, 0xb8, 0x8f, 0x11, 0x13, 0xb9, 0x6d, 0xf1, 0x98, 0x78, 0x59, 0x2b, 0x33,
	0x8b, 0xfa, 0x4f, 0x06, 0x2b, 0xe3, 0x46, 0x9f, 0x29, 0x59, 0xf2, 0x18, 0xb4, 0xe2, 0x97, 0xd0,
	0xd8, 0x92, 0x59, 0xa2, 0x4e, 0x37, 0x67, 0xbf, 0x1c, 0x0f, 0x65, 0xcc, 0x44, 0xe0, 0xd7, 0xb0,
	0x8e, 0x2e, 0x65, 0x0c, 0x76, 0xe7, 0xe9, 0xe3, 0xc9, 0x65, 0x12, 0x55, 0x57, 0xcb, 0x85, 0xaa,
	0x5a, 0x66, 0xfe, 0x9e, 0x78, 0x0b, 0xf5, 0xce, 0x92, 0xa8, 0x3b, 0x26, 0x99, 0xf9, 0x1e, 0x0b,
	0x82, 0x41, 0x1c, 0x4f, 0x08, 0x86, 0xab, 0x1e, 0xc4, 0x7f, 0xad, 0x79, 0x03, 0xd5, 0xbd, 0x6a,
	0x8f, 0x5e, 0x9a, 0xf2, 0xa6, 0x9b, 0xaf, 0x00, 0x00, 0x00, 0xff, 0xff, 0x94, 0x4a, 0xd5, 0x13,
	0x39, 0x01, 0x00, 0x00,
}
