// Code generated by protoc-gen-go. DO NOT EDIT.
// source: outgoingPB.proto

package OutgoingPB

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	any "github.com/golang/protobuf/ptypes/any"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type HTTPStatusPB int32

const (
	HTTPStatusPB_SUCCESS                    HTTPStatusPB = 0
	HTTPStatusPB_BAD_REQUEST                HTTPStatusPB = 1
	HTTPStatusPB_MISSING_REQUIRED_PARAMETER HTTPStatusPB = 2
	HTTPStatusPB_MALFORMED_PARAMETER        HTTPStatusPB = 3
	HTTPStatusPB_INVALID_PARAMETER          HTTPStatusPB = 4
	HTTPStatusPB_UNAUTHORIZED_REQUEST       HTTPStatusPB = 5
	HTTPStatusPB_FORBIDDEN_REQUEST          HTTPStatusPB = 6
	HTTPStatusPB_NOT_FOUND                  HTTPStatusPB = 7
	HTTPStatusPB_INTERNAL_SERVER_ERROR      HTTPStatusPB = 8
)

var HTTPStatusPB_name = map[int32]string{
	0: "SUCCESS",
	1: "BAD_REQUEST",
	2: "MISSING_REQUIRED_PARAMETER",
	3: "MALFORMED_PARAMETER",
	4: "INVALID_PARAMETER",
	5: "UNAUTHORIZED_REQUEST",
	6: "FORBIDDEN_REQUEST",
	7: "NOT_FOUND",
	8: "INTERNAL_SERVER_ERROR",
}

var HTTPStatusPB_value = map[string]int32{
	"SUCCESS":                    0,
	"BAD_REQUEST":                1,
	"MISSING_REQUIRED_PARAMETER": 2,
	"MALFORMED_PARAMETER":        3,
	"INVALID_PARAMETER":          4,
	"UNAUTHORIZED_REQUEST":       5,
	"FORBIDDEN_REQUEST":          6,
	"NOT_FOUND":                  7,
	"INTERNAL_SERVER_ERROR":      8,
}

func (x HTTPStatusPB) String() string {
	return proto.EnumName(HTTPStatusPB_name, int32(x))
}

func (HTTPStatusPB) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_7545a4103aff42fe, []int{0}
}

type DTOValidationErrorCodePB int32

const (
	DTOValidationErrorCodePB_DTO_FIELD_NOT_NULL              DTOValidationErrorCodePB = 0
	DTOValidationErrorCodePB_DTO_FIELD_NOT_EMPTY             DTOValidationErrorCodePB = 1
	DTOValidationErrorCodePB_DTO_FIELD_STRING                DTOValidationErrorCodePB = 2
	DTOValidationErrorCodePB_DTO_AUTH_PROVIDER_NOT_SUPPORTED DTOValidationErrorCodePB = 3
	DTOValidationErrorCodePB_DTO_PERS_TEST_MUST_ARRAY        DTOValidationErrorCodePB = 4
	DTOValidationErrorCodePB_DTO_PERS_TEST_SIZE              DTOValidationErrorCodePB = 5
	DTOValidationErrorCodePB_DTO_PERS_TEST_TYPE              DTOValidationErrorCodePB = 6
	DTOValidationErrorCodePB_DTO_FIELD_NUMBER                DTOValidationErrorCodePB = 7
	DTOValidationErrorCodePB_DTO_FIELD_NUMBER_LIMIT          DTOValidationErrorCodePB = 8
	DTOValidationErrorCodePB_DTO_LAT_LON_TOGETHER            DTOValidationErrorCodePB = 9
	DTOValidationErrorCodePB_DTO_MIN_AGE                     DTOValidationErrorCodePB = 10
	DTOValidationErrorCodePB_DTO_ANONMESS_TYPE_ERR           DTOValidationErrorCodePB = 11
	DTOValidationErrorCodePB_DTO_FLIED_MUST_BE_OBJECT_ID     DTOValidationErrorCodePB = 12
	DTOValidationErrorCodePB_DTO_LOW_AND_HIGH_AGE_FAIL       DTOValidationErrorCodePB = 13
)

var DTOValidationErrorCodePB_name = map[int32]string{
	0:  "DTO_FIELD_NOT_NULL",
	1:  "DTO_FIELD_NOT_EMPTY",
	2:  "DTO_FIELD_STRING",
	3:  "DTO_AUTH_PROVIDER_NOT_SUPPORTED",
	4:  "DTO_PERS_TEST_MUST_ARRAY",
	5:  "DTO_PERS_TEST_SIZE",
	6:  "DTO_PERS_TEST_TYPE",
	7:  "DTO_FIELD_NUMBER",
	8:  "DTO_FIELD_NUMBER_LIMIT",
	9:  "DTO_LAT_LON_TOGETHER",
	10: "DTO_MIN_AGE",
	11: "DTO_ANONMESS_TYPE_ERR",
	12: "DTO_FLIED_MUST_BE_OBJECT_ID",
	13: "DTO_LOW_AND_HIGH_AGE_FAIL",
}

var DTOValidationErrorCodePB_value = map[string]int32{
	"DTO_FIELD_NOT_NULL":              0,
	"DTO_FIELD_NOT_EMPTY":             1,
	"DTO_FIELD_STRING":                2,
	"DTO_AUTH_PROVIDER_NOT_SUPPORTED": 3,
	"DTO_PERS_TEST_MUST_ARRAY":        4,
	"DTO_PERS_TEST_SIZE":              5,
	"DTO_PERS_TEST_TYPE":              6,
	"DTO_FIELD_NUMBER":                7,
	"DTO_FIELD_NUMBER_LIMIT":          8,
	"DTO_LAT_LON_TOGETHER":            9,
	"DTO_MIN_AGE":                     10,
	"DTO_ANONMESS_TYPE_ERR":           11,
	"DTO_FLIED_MUST_BE_OBJECT_ID":     12,
	"DTO_LOW_AND_HIGH_AGE_FAIL":       13,
}

func (x DTOValidationErrorCodePB) String() string {
	return proto.EnumName(DTOValidationErrorCodePB_name, int32(x))
}

func (DTOValidationErrorCodePB) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_7545a4103aff42fe, []int{1}
}

// start search response
type SearchPBStatus int32

const (
	SearchPBStatus_IN_WAITING SearchPBStatus = 0
)

var SearchPBStatus_name = map[int32]string{
	0: "IN_WAITING",
}

var SearchPBStatus_value = map[string]int32{
	"IN_WAITING": 0,
}

func (x SearchPBStatus) String() string {
	return proto.EnumName(SearchPBStatus_name, int32(x))
}

func (SearchPBStatus) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_7545a4103aff42fe, []int{2}
}

type ServerResponseMessagePB struct {
	Code                 HTTPStatusPB `protobuf:"varint,1,opt,name=code,proto3,enum=OutgoingPB.HTTPStatusPB" json:"code,omitempty"`
	NewKey               string       `protobuf:"bytes,2,opt,name=newKey,proto3" json:"newKey,omitempty"`
	Data                 *any.Any     `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *ServerResponseMessagePB) Reset()         { *m = ServerResponseMessagePB{} }
func (m *ServerResponseMessagePB) String() string { return proto.CompactTextString(m) }
func (*ServerResponseMessagePB) ProtoMessage()    {}
func (*ServerResponseMessagePB) Descriptor() ([]byte, []int) {
	return fileDescriptor_7545a4103aff42fe, []int{0}
}

func (m *ServerResponseMessagePB) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ServerResponseMessagePB.Unmarshal(m, b)
}
func (m *ServerResponseMessagePB) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ServerResponseMessagePB.Marshal(b, m, deterministic)
}
func (m *ServerResponseMessagePB) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ServerResponseMessagePB.Merge(m, src)
}
func (m *ServerResponseMessagePB) XXX_Size() int {
	return xxx_messageInfo_ServerResponseMessagePB.Size(m)
}
func (m *ServerResponseMessagePB) XXX_DiscardUnknown() {
	xxx_messageInfo_ServerResponseMessagePB.DiscardUnknown(m)
}

var xxx_messageInfo_ServerResponseMessagePB proto.InternalMessageInfo

func (m *ServerResponseMessagePB) GetCode() HTTPStatusPB {
	if m != nil {
		return m.Code
	}
	return HTTPStatusPB_SUCCESS
}

func (m *ServerResponseMessagePB) GetNewKey() string {
	if m != nil {
		return m.NewKey
	}
	return ""
}

func (m *ServerResponseMessagePB) GetData() *any.Any {
	if m != nil {
		return m.Data
	}
	return nil
}

type DTOValidationResponsePB struct {
	Code                 DTOValidationErrorCodePB `protobuf:"varint,1,opt,name=code,proto3,enum=OutgoingPB.DTOValidationErrorCodePB" json:"code,omitempty"`
	DtoName              string                   `protobuf:"bytes,2,opt,name=dtoName,proto3" json:"dtoName,omitempty"`
	DtoField             string                   `protobuf:"bytes,3,opt,name=dtoField,proto3" json:"dtoField,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                 `json:"-"`
	XXX_unrecognized     []byte                   `json:"-"`
	XXX_sizecache        int32                    `json:"-"`
}

func (m *DTOValidationResponsePB) Reset()         { *m = DTOValidationResponsePB{} }
func (m *DTOValidationResponsePB) String() string { return proto.CompactTextString(m) }
func (*DTOValidationResponsePB) ProtoMessage()    {}
func (*DTOValidationResponsePB) Descriptor() ([]byte, []int) {
	return fileDescriptor_7545a4103aff42fe, []int{1}
}

func (m *DTOValidationResponsePB) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DTOValidationResponsePB.Unmarshal(m, b)
}
func (m *DTOValidationResponsePB) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DTOValidationResponsePB.Marshal(b, m, deterministic)
}
func (m *DTOValidationResponsePB) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DTOValidationResponsePB.Merge(m, src)
}
func (m *DTOValidationResponsePB) XXX_Size() int {
	return xxx_messageInfo_DTOValidationResponsePB.Size(m)
}
func (m *DTOValidationResponsePB) XXX_DiscardUnknown() {
	xxx_messageInfo_DTOValidationResponsePB.DiscardUnknown(m)
}

var xxx_messageInfo_DTOValidationResponsePB proto.InternalMessageInfo

func (m *DTOValidationResponsePB) GetCode() DTOValidationErrorCodePB {
	if m != nil {
		return m.Code
	}
	return DTOValidationErrorCodePB_DTO_FIELD_NOT_NULL
}

func (m *DTOValidationResponsePB) GetDtoName() string {
	if m != nil {
		return m.DtoName
	}
	return ""
}

func (m *DTOValidationResponsePB) GetDtoField() string {
	if m != nil {
		return m.DtoField
	}
	return ""
}

type CollectionDTOValidationResponsePB struct {
	DtoValidation        []*DTOValidationResponsePB `protobuf:"bytes,1,rep,name=dtoValidation,proto3" json:"dtoValidation,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                   `json:"-"`
	XXX_unrecognized     []byte                     `json:"-"`
	XXX_sizecache        int32                      `json:"-"`
}

func (m *CollectionDTOValidationResponsePB) Reset()         { *m = CollectionDTOValidationResponsePB{} }
func (m *CollectionDTOValidationResponsePB) String() string { return proto.CompactTextString(m) }
func (*CollectionDTOValidationResponsePB) ProtoMessage()    {}
func (*CollectionDTOValidationResponsePB) Descriptor() ([]byte, []int) {
	return fileDescriptor_7545a4103aff42fe, []int{2}
}

func (m *CollectionDTOValidationResponsePB) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CollectionDTOValidationResponsePB.Unmarshal(m, b)
}
func (m *CollectionDTOValidationResponsePB) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CollectionDTOValidationResponsePB.Marshal(b, m, deterministic)
}
func (m *CollectionDTOValidationResponsePB) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CollectionDTOValidationResponsePB.Merge(m, src)
}
func (m *CollectionDTOValidationResponsePB) XXX_Size() int {
	return xxx_messageInfo_CollectionDTOValidationResponsePB.Size(m)
}
func (m *CollectionDTOValidationResponsePB) XXX_DiscardUnknown() {
	xxx_messageInfo_CollectionDTOValidationResponsePB.DiscardUnknown(m)
}

var xxx_messageInfo_CollectionDTOValidationResponsePB proto.InternalMessageInfo

func (m *CollectionDTOValidationResponsePB) GetDtoValidation() []*DTOValidationResponsePB {
	if m != nil {
		return m.DtoValidation
	}
	return nil
}

type SimpleMessagePB struct {
	Message              string   `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SimpleMessagePB) Reset()         { *m = SimpleMessagePB{} }
func (m *SimpleMessagePB) String() string { return proto.CompactTextString(m) }
func (*SimpleMessagePB) ProtoMessage()    {}
func (*SimpleMessagePB) Descriptor() ([]byte, []int) {
	return fileDescriptor_7545a4103aff42fe, []int{3}
}

func (m *SimpleMessagePB) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SimpleMessagePB.Unmarshal(m, b)
}
func (m *SimpleMessagePB) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SimpleMessagePB.Marshal(b, m, deterministic)
}
func (m *SimpleMessagePB) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SimpleMessagePB.Merge(m, src)
}
func (m *SimpleMessagePB) XXX_Size() int {
	return xxx_messageInfo_SimpleMessagePB.Size(m)
}
func (m *SimpleMessagePB) XXX_DiscardUnknown() {
	xxx_messageInfo_SimpleMessagePB.DiscardUnknown(m)
}

var xxx_messageInfo_SimpleMessagePB proto.InternalMessageInfo

func (m *SimpleMessagePB) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

type AuthResponsePB struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Birthday             string   `protobuf:"bytes,2,opt,name=birthday,proto3" json:"birthday,omitempty"`
	Gender               string   `protobuf:"bytes,3,opt,name=gender,proto3" json:"gender,omitempty"`
	FirstName            string   `protobuf:"bytes,4,opt,name=first_name,json=firstName,proto3" json:"first_name,omitempty"`
	Email                string   `protobuf:"bytes,5,opt,name=email,proto3" json:"email,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AuthResponsePB) Reset()         { *m = AuthResponsePB{} }
func (m *AuthResponsePB) String() string { return proto.CompactTextString(m) }
func (*AuthResponsePB) ProtoMessage()    {}
func (*AuthResponsePB) Descriptor() ([]byte, []int) {
	return fileDescriptor_7545a4103aff42fe, []int{4}
}

func (m *AuthResponsePB) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AuthResponsePB.Unmarshal(m, b)
}
func (m *AuthResponsePB) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AuthResponsePB.Marshal(b, m, deterministic)
}
func (m *AuthResponsePB) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AuthResponsePB.Merge(m, src)
}
func (m *AuthResponsePB) XXX_Size() int {
	return xxx_messageInfo_AuthResponsePB.Size(m)
}
func (m *AuthResponsePB) XXX_DiscardUnknown() {
	xxx_messageInfo_AuthResponsePB.DiscardUnknown(m)
}

var xxx_messageInfo_AuthResponsePB proto.InternalMessageInfo

func (m *AuthResponsePB) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *AuthResponsePB) GetBirthday() string {
	if m != nil {
		return m.Birthday
	}
	return ""
}

func (m *AuthResponsePB) GetGender() string {
	if m != nil {
		return m.Gender
	}
	return ""
}

func (m *AuthResponsePB) GetFirstName() string {
	if m != nil {
		return m.FirstName
	}
	return ""
}

func (m *AuthResponsePB) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

type ServerIdsPB struct {
	ServerId             string   `protobuf:"bytes,1,opt,name=serverId,proto3" json:"serverId,omitempty"`
	Jid                  string   `protobuf:"bytes,2,opt,name=jid,proto3" json:"jid,omitempty"`
	Username             string   `protobuf:"bytes,3,opt,name=username,proto3" json:"username,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ServerIdsPB) Reset()         { *m = ServerIdsPB{} }
func (m *ServerIdsPB) String() string { return proto.CompactTextString(m) }
func (*ServerIdsPB) ProtoMessage()    {}
func (*ServerIdsPB) Descriptor() ([]byte, []int) {
	return fileDescriptor_7545a4103aff42fe, []int{5}
}

func (m *ServerIdsPB) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ServerIdsPB.Unmarshal(m, b)
}
func (m *ServerIdsPB) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ServerIdsPB.Marshal(b, m, deterministic)
}
func (m *ServerIdsPB) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ServerIdsPB.Merge(m, src)
}
func (m *ServerIdsPB) XXX_Size() int {
	return xxx_messageInfo_ServerIdsPB.Size(m)
}
func (m *ServerIdsPB) XXX_DiscardUnknown() {
	xxx_messageInfo_ServerIdsPB.DiscardUnknown(m)
}

var xxx_messageInfo_ServerIdsPB proto.InternalMessageInfo

func (m *ServerIdsPB) GetServerId() string {
	if m != nil {
		return m.ServerId
	}
	return ""
}

func (m *ServerIdsPB) GetJid() string {
	if m != nil {
		return m.Jid
	}
	return ""
}

func (m *ServerIdsPB) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

type RegistrationResponsePB struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Personality          string   `protobuf:"bytes,2,opt,name=personality,proto3" json:"personality,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RegistrationResponsePB) Reset()         { *m = RegistrationResponsePB{} }
func (m *RegistrationResponsePB) String() string { return proto.CompactTextString(m) }
func (*RegistrationResponsePB) ProtoMessage()    {}
func (*RegistrationResponsePB) Descriptor() ([]byte, []int) {
	return fileDescriptor_7545a4103aff42fe, []int{6}
}

func (m *RegistrationResponsePB) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RegistrationResponsePB.Unmarshal(m, b)
}
func (m *RegistrationResponsePB) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RegistrationResponsePB.Marshal(b, m, deterministic)
}
func (m *RegistrationResponsePB) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RegistrationResponsePB.Merge(m, src)
}
func (m *RegistrationResponsePB) XXX_Size() int {
	return xxx_messageInfo_RegistrationResponsePB.Size(m)
}
func (m *RegistrationResponsePB) XXX_DiscardUnknown() {
	xxx_messageInfo_RegistrationResponsePB.DiscardUnknown(m)
}

var xxx_messageInfo_RegistrationResponsePB proto.InternalMessageInfo

func (m *RegistrationResponsePB) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *RegistrationResponsePB) GetPersonality() string {
	if m != nil {
		return m.Personality
	}
	return ""
}

type SessionPB struct {
	ServerSession        string   `protobuf:"bytes,1,opt,name=serverSession,proto3" json:"serverSession,omitempty"`
	ChatServerToken      string   `protobuf:"bytes,2,opt,name=chatServerToken,proto3" json:"chatServerToken,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SessionPB) Reset()         { *m = SessionPB{} }
func (m *SessionPB) String() string { return proto.CompactTextString(m) }
func (*SessionPB) ProtoMessage()    {}
func (*SessionPB) Descriptor() ([]byte, []int) {
	return fileDescriptor_7545a4103aff42fe, []int{7}
}

func (m *SessionPB) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SessionPB.Unmarshal(m, b)
}
func (m *SessionPB) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SessionPB.Marshal(b, m, deterministic)
}
func (m *SessionPB) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SessionPB.Merge(m, src)
}
func (m *SessionPB) XXX_Size() int {
	return xxx_messageInfo_SessionPB.Size(m)
}
func (m *SessionPB) XXX_DiscardUnknown() {
	xxx_messageInfo_SessionPB.DiscardUnknown(m)
}

var xxx_messageInfo_SessionPB proto.InternalMessageInfo

func (m *SessionPB) GetServerSession() string {
	if m != nil {
		return m.ServerSession
	}
	return ""
}

func (m *SessionPB) GetChatServerToken() string {
	if m != nil {
		return m.ChatServerToken
	}
	return ""
}

type InWaitingSearchPB struct {
	TTLDuration          int64    `protobuf:"varint,1,opt,name=TTLDuration,proto3" json:"TTLDuration,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *InWaitingSearchPB) Reset()         { *m = InWaitingSearchPB{} }
func (m *InWaitingSearchPB) String() string { return proto.CompactTextString(m) }
func (*InWaitingSearchPB) ProtoMessage()    {}
func (*InWaitingSearchPB) Descriptor() ([]byte, []int) {
	return fileDescriptor_7545a4103aff42fe, []int{8}
}

func (m *InWaitingSearchPB) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_InWaitingSearchPB.Unmarshal(m, b)
}
func (m *InWaitingSearchPB) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_InWaitingSearchPB.Marshal(b, m, deterministic)
}
func (m *InWaitingSearchPB) XXX_Merge(src proto.Message) {
	xxx_messageInfo_InWaitingSearchPB.Merge(m, src)
}
func (m *InWaitingSearchPB) XXX_Size() int {
	return xxx_messageInfo_InWaitingSearchPB.Size(m)
}
func (m *InWaitingSearchPB) XXX_DiscardUnknown() {
	xxx_messageInfo_InWaitingSearchPB.DiscardUnknown(m)
}

var xxx_messageInfo_InWaitingSearchPB proto.InternalMessageInfo

func (m *InWaitingSearchPB) GetTTLDuration() int64 {
	if m != nil {
		return m.TTLDuration
	}
	return 0
}

type SearchPB struct {
	Status               SearchPBStatus     `protobuf:"varint,1,opt,name=status,proto3,enum=OutgoingPB.SearchPBStatus" json:"status,omitempty"`
	InWaitingSearchPB    *InWaitingSearchPB `protobuf:"bytes,2,opt,name=inWaitingSearchPB,proto3" json:"inWaitingSearchPB,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *SearchPB) Reset()         { *m = SearchPB{} }
func (m *SearchPB) String() string { return proto.CompactTextString(m) }
func (*SearchPB) ProtoMessage()    {}
func (*SearchPB) Descriptor() ([]byte, []int) {
	return fileDescriptor_7545a4103aff42fe, []int{9}
}

func (m *SearchPB) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SearchPB.Unmarshal(m, b)
}
func (m *SearchPB) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SearchPB.Marshal(b, m, deterministic)
}
func (m *SearchPB) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SearchPB.Merge(m, src)
}
func (m *SearchPB) XXX_Size() int {
	return xxx_messageInfo_SearchPB.Size(m)
}
func (m *SearchPB) XXX_DiscardUnknown() {
	xxx_messageInfo_SearchPB.DiscardUnknown(m)
}

var xxx_messageInfo_SearchPB proto.InternalMessageInfo

func (m *SearchPB) GetStatus() SearchPBStatus {
	if m != nil {
		return m.Status
	}
	return SearchPBStatus_IN_WAITING
}

func (m *SearchPB) GetInWaitingSearchPB() *InWaitingSearchPB {
	if m != nil {
		return m.InWaitingSearchPB
	}
	return nil
}

func init() {
	proto.RegisterEnum("OutgoingPB.HTTPStatusPB", HTTPStatusPB_name, HTTPStatusPB_value)
	proto.RegisterEnum("OutgoingPB.DTOValidationErrorCodePB", DTOValidationErrorCodePB_name, DTOValidationErrorCodePB_value)
	proto.RegisterEnum("OutgoingPB.SearchPBStatus", SearchPBStatus_name, SearchPBStatus_value)
	proto.RegisterType((*ServerResponseMessagePB)(nil), "OutgoingPB.ServerResponseMessagePB")
	proto.RegisterType((*DTOValidationResponsePB)(nil), "OutgoingPB.DTOValidationResponsePB")
	proto.RegisterType((*CollectionDTOValidationResponsePB)(nil), "OutgoingPB.CollectionDTOValidationResponsePB")
	proto.RegisterType((*SimpleMessagePB)(nil), "OutgoingPB.SimpleMessagePB")
	proto.RegisterType((*AuthResponsePB)(nil), "OutgoingPB.AuthResponsePB")
	proto.RegisterType((*ServerIdsPB)(nil), "OutgoingPB.ServerIdsPB")
	proto.RegisterType((*RegistrationResponsePB)(nil), "OutgoingPB.RegistrationResponsePB")
	proto.RegisterType((*SessionPB)(nil), "OutgoingPB.SessionPB")
	proto.RegisterType((*InWaitingSearchPB)(nil), "OutgoingPB.InWaitingSearchPB")
	proto.RegisterType((*SearchPB)(nil), "OutgoingPB.SearchPB")
}

func init() { proto.RegisterFile("outgoingPB.proto", fileDescriptor_7545a4103aff42fe) }

var fileDescriptor_7545a4103aff42fe = []byte{
	// 928 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x95, 0x5b, 0x4f, 0xe3, 0x46,
	0x14, 0xc7, 0x31, 0xe1, 0x96, 0x93, 0x05, 0x86, 0x29, 0xcb, 0x66, 0x69, 0xe9, 0x66, 0xb3, 0xfb,
	0x10, 0xd1, 0x2a, 0x48, 0x54, 0x95, 0xfa, 0x6a, 0xe3, 0x09, 0xcc, 0xae, 0x6f, 0x1d, 0x4f, 0x40,
	0x6c, 0x1f, 0x46, 0x06, 0xcf, 0x06, 0xb7, 0xc1, 0x46, 0xb6, 0xd3, 0x8a, 0x8f, 0x50, 0xb5, 0xdf,
	0xaf, 0x5f, 0xa7, 0x9a, 0x89, 0x9d, 0x0b, 0x88, 0xb7, 0x9c, 0xff, 0xb9, 0xfd, 0xce, 0x99, 0x99,
	0x18, 0x50, 0x36, 0x29, 0x47, 0x59, 0x92, 0x8e, 0x02, 0xab, 0xff, 0x90, 0x67, 0x65, 0x86, 0xc1,
	0x9f, 0x29, 0x87, 0xef, 0x93, 0xf4, 0x76, 0x3c, 0x89, 0xe5, 0xc9, 0x28, 0xcb, 0x46, 0x63, 0x79,
	0xa2, 0x23, 0x6e, 0x26, 0x5f, 0x4f, 0xa2, 0xf4, 0x71, 0x1a, 0xde, 0xfd, 0xdb, 0x80, 0x37, 0xa1,
	0xcc, 0xff, 0x94, 0x39, 0x93, 0xc5, 0x43, 0x96, 0x16, 0xd2, 0x95, 0x45, 0x11, 0x8d, 0x64, 0x60,
	0xe1, 0x1f, 0x61, 0xed, 0x36, 0x8b, 0x65, 0xdb, 0xe8, 0x18, 0xbd, 0x9d, 0xd3, 0x76, 0x7f, 0x5e,
	0xb9, 0x7f, 0xc1, 0x79, 0x10, 0x96, 0x51, 0x39, 0x29, 0x02, 0x8b, 0xe9, 0x28, 0x7c, 0x00, 0x1b,
	0xa9, 0xfc, 0xeb, 0xb3, 0x7c, 0x6c, 0xaf, 0x76, 0x8c, 0x5e, 0x93, 0x55, 0x16, 0xee, 0xc1, 0x5a,
	0x1c, 0x95, 0x51, 0xbb, 0xd1, 0x31, 0x7a, 0xad, 0xd3, 0xfd, 0xfe, 0x94, 0xa5, 0x5f, 0xb3, 0xf4,
	0xcd, 0xf4, 0x91, 0xe9, 0x08, 0xcd, 0x62, 0x73, 0xff, 0x32, 0x1a, 0x27, 0x71, 0x54, 0x26, 0x59,
	0x5a, 0x23, 0x05, 0x16, 0xfe, 0x65, 0x89, 0xe5, 0xe3, 0x22, 0xcb, 0x52, 0x0a, 0xc9, 0xf3, 0x2c,
	0x3f, 0xcb, 0x62, 0x39, 0xe3, 0x6a, 0xc3, 0x66, 0x5c, 0x66, 0x5e, 0x74, 0x2f, 0x2b, 0xb0, 0xda,
	0xc4, 0x87, 0xb0, 0x15, 0x97, 0xd9, 0x20, 0x91, 0xe3, 0x58, 0xd3, 0x35, 0xd9, 0xcc, 0xee, 0xa6,
	0xf0, 0xfe, 0x2c, 0x1b, 0x8f, 0xe5, 0xad, 0x2a, 0xfa, 0x12, 0x14, 0x85, 0xed, 0xb8, 0xcc, 0xe6,
	0xae, 0xb6, 0xd1, 0x69, 0xf4, 0x5a, 0xa7, 0x1f, 0x5e, 0xa4, 0x9b, 0xe7, 0xb2, 0xe5, 0xcc, 0xee,
	0x0f, 0xb0, 0x1b, 0x26, 0xf7, 0x0f, 0xe3, 0x85, 0xf5, 0xb7, 0x61, 0xf3, 0x7e, 0x6a, 0xe8, 0xa9,
	0x9b, 0xac, 0x36, 0xd5, 0xa2, 0x76, 0xcc, 0x49, 0x79, 0xb7, 0x80, 0xb2, 0x03, 0xab, 0x49, 0x5c,
	0xc5, 0xad, 0x26, 0xb1, 0x9a, 0xed, 0x26, 0xc9, 0xcb, 0xbb, 0x38, 0xaa, 0xcf, 0x63, 0x66, 0xab,
	0x93, 0x1a, 0xc9, 0x34, 0x96, 0x79, 0x35, 0x75, 0x65, 0xe1, 0x23, 0x80, 0xaf, 0x49, 0x5e, 0x94,
	0x22, 0x55, 0xcb, 0x5a, 0xd3, 0xbe, 0xa6, 0x56, 0xf4, 0xba, 0xf6, 0x61, 0x5d, 0xde, 0x47, 0xc9,
	0xb8, 0xbd, 0xae, 0x3d, 0x53, 0xa3, 0x7b, 0x05, 0xad, 0xe9, 0xfd, 0xa1, 0x71, 0x11, 0x58, 0xaa,
	0x6f, 0x51, 0x99, 0x15, 0xcd, 0xcc, 0xc6, 0x08, 0x1a, 0xbf, 0x27, 0x71, 0x85, 0xa3, 0x7e, 0xaa,
	0xe8, 0x49, 0x21, 0x73, 0xdd, 0xaf, 0x3a, 0x81, 0xda, 0xee, 0x7e, 0x82, 0x03, 0x26, 0x47, 0x49,
	0x51, 0xe6, 0x4f, 0xd7, 0xfe, 0x74, 0xd6, 0x0e, 0xb4, 0x1e, 0x64, 0x5e, 0x64, 0x69, 0x34, 0x4e,
	0xca, 0x7a, 0xdc, 0x45, 0xa9, 0xfb, 0x1b, 0x34, 0x43, 0x59, 0x14, 0x49, 0x96, 0x06, 0x16, 0xfe,
	0x08, 0xdb, 0x53, 0xa4, 0x4a, 0xaa, 0x2a, 0x2d, 0x8b, 0xb8, 0x07, 0xbb, 0xb7, 0x77, 0x51, 0x39,
	0x9d, 0x8d, 0x67, 0x7f, 0xc8, 0xb4, 0x2a, 0xfc, 0x54, 0xee, 0xfe, 0x0c, 0x7b, 0x34, 0xbd, 0x8a,
	0x92, 0x32, 0x49, 0x47, 0xa1, 0x8c, 0xf2, 0xdb, 0xbb, 0xc0, 0x52, 0x4c, 0x9c, 0x3b, 0xf6, 0x24,
	0xaf, 0x2f, 0x86, 0xd1, 0x6b, 0xb0, 0x45, 0xa9, 0xfb, 0x8f, 0x01, 0x5b, 0xb3, 0xf0, 0x53, 0xd8,
	0x28, 0xf4, 0x73, 0xaa, 0x2e, 0xf8, 0xe1, 0xe2, 0x15, 0xaa, 0xa3, 0xa6, 0x0f, 0x8e, 0x55, 0x91,
	0xf8, 0x33, 0xec, 0x25, 0x4f, 0xfb, 0x6a, 0xc6, 0xd6, 0xe9, 0xd1, 0x62, 0xfa, 0x33, 0x38, 0xf6,
	0x3c, 0xef, 0xf8, 0x3f, 0x03, 0x5e, 0x2d, 0x3e, 0x6a, 0xdc, 0x82, 0xcd, 0x70, 0x78, 0x76, 0x46,
	0xc2, 0x10, 0xad, 0xe0, 0x5d, 0x68, 0x59, 0xa6, 0x2d, 0x18, 0xf9, 0x75, 0x48, 0x42, 0x8e, 0x0c,
	0xfc, 0x3d, 0x1c, 0xba, 0x34, 0x0c, 0xa9, 0x77, 0xae, 0x45, 0xca, 0x88, 0x2d, 0x02, 0x93, 0x99,
	0x2e, 0xe1, 0x84, 0xa1, 0x55, 0xfc, 0x06, 0xbe, 0x71, 0x4d, 0x67, 0xe0, 0x33, 0x77, 0xc9, 0xd1,
	0xc0, 0xaf, 0x61, 0x8f, 0x7a, 0x97, 0xa6, 0x43, 0x17, 0xe5, 0x35, 0xdc, 0x86, 0xfd, 0xa1, 0x67,
	0x0e, 0xf9, 0x85, 0xcf, 0xe8, 0x17, 0x32, 0xef, 0xb4, 0xae, 0x12, 0x06, 0x3e, 0xb3, 0xa8, 0x6d,
	0x13, 0x6f, 0x26, 0x6f, 0xe0, 0x6d, 0x68, 0x7a, 0x3e, 0x17, 0x03, 0x7f, 0xe8, 0xd9, 0x68, 0x13,
	0xbf, 0x85, 0xd7, 0xd4, 0xe3, 0x84, 0x79, 0xa6, 0x23, 0x42, 0xc2, 0x2e, 0x09, 0x13, 0x84, 0x31,
	0x9f, 0xa1, 0xad, 0xe3, 0x7f, 0x1b, 0xd0, 0x7e, 0xe9, 0x2f, 0x02, 0x1f, 0x00, 0xb6, 0xb9, 0x2f,
	0x06, 0x94, 0x38, 0xb6, 0x50, 0x05, 0xbd, 0xa1, 0xe3, 0xa0, 0x15, 0xc5, 0xbf, 0xac, 0x13, 0x37,
	0xe0, 0xd7, 0xc8, 0xc0, 0xfb, 0x80, 0xe6, 0x8e, 0x90, 0x33, 0xea, 0x9d, 0xa3, 0x55, 0xfc, 0x01,
	0xde, 0x29, 0x55, 0x0d, 0x20, 0x02, 0xe6, 0x5f, 0x52, 0x9b, 0x30, 0x9d, 0x16, 0x0e, 0x83, 0xc0,
	0x67, 0x9c, 0xd8, 0xa8, 0x81, 0xbf, 0xd3, 0x1c, 0x22, 0x20, 0x2c, 0x14, 0x9c, 0x84, 0x5c, 0xb8,
	0xc3, 0x90, 0x0b, 0x93, 0x31, 0xf3, 0x1a, 0xad, 0xd5, 0x24, 0x73, 0x6f, 0x48, 0xbf, 0x10, 0xb4,
	0xfe, 0x5c, 0xe7, 0xd7, 0x01, 0x41, 0x1b, 0xcb, 0x20, 0xde, 0xd0, 0xb5, 0x08, 0x43, 0x9b, 0xf8,
	0x10, 0x0e, 0x9e, 0xaa, 0xc2, 0xa1, 0x2e, 0xe5, 0x68, 0x4b, 0xed, 0x58, 0xf9, 0x1c, 0x93, 0x0b,
	0xc7, 0xf7, 0x04, 0xf7, 0xcf, 0x09, 0xbf, 0x20, 0x0c, 0x35, 0xd5, 0xf1, 0x2a, 0x8f, 0x4b, 0x3d,
	0x61, 0x9e, 0x13, 0x04, 0x6a, 0x9d, 0x7a, 0x1e, 0xcf, 0xf7, 0x5c, 0x12, 0x86, 0xba, 0xa7, 0x5a,
	0x28, 0x6a, 0xe1, 0x77, 0xf0, 0xad, 0xee, 0xe0, 0x50, 0x62, 0x4f, 0x27, 0xb0, 0x88, 0xf0, 0xad,
	0x4f, 0xe4, 0x8c, 0x0b, 0x6a, 0xa3, 0x57, 0xf8, 0x08, 0xde, 0xea, 0x36, 0xfe, 0x95, 0x30, 0x3d,
	0x5b, 0x5c, 0xd0, 0xf3, 0x0b, 0x55, 0x55, 0x0c, 0x4c, 0xea, 0xa0, 0xed, 0xe3, 0x0e, 0xec, 0x2c,
	0xdf, 0x67, 0xbc, 0x03, 0x40, 0x3d, 0x71, 0x65, 0x52, 0xae, 0x96, 0xb9, 0x72, 0xb3, 0xa1, 0x3f,
	0x0d, 0x3f, 0xfd, 0x1f, 0x00, 0x00, 0xff, 0xff, 0xee, 0x7b, 0x82, 0x2a, 0xdc, 0x06, 0x00, 0x00,
}
